## **DATA CRAWLING TWITTER/X**

In [1]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
#Twitter Auth Token

twitter_auth_token = '9da35f0cc46049ea44e4e88a2e7502df17cb82c0'

In [3]:
!pip install pandas

!sudo apt-get update
!sudo apt-get install -y ca-certificates curl gnupg
!sudo mkdir -p /etc/apt/keyrings
!curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg

!NODE_MAJOR=20 && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list

!sudo apt-get update
!sudo apt-get install nodejs -y

!node -v

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Hit:1 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:3 https://cli.github.com/packages stable InRelease [3,917 B]
Get:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:5 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:6 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:7 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Get:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,115 kB]
Get:10 https://cli.github.com/packages stable/main amd64 Packages [357 B]
Get:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease [24.6 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [70.9 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [6,870 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,613 kB]
Get:15 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,916 kB]
Get:16 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [85.2 kB]
Get:17 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [9,793 kB]
Get:18 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [6,643 kB]
Get:19 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [39.2 kB]
Get:20 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy/main amd64 Packages [75.3 kB]
Get:21 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,772 kB]
Get:22 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,302 kB]
Get:23 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [62.6 kB]
Fetched 37.8 MB in 4s (9,767 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ca-certificates is already the newest version (20240203~22.04.1).
gnupg is already the newest version (2.2.27-3ubuntu2.5).
gnupg set to manually installed.
Suggested packages:
  libcurl4-doc libidn11-dev libldap2-dev librtmp-dev
The following packages will be upgraded:
  curl libcurl4 libcurl4-openssl-dev
3 upgraded, 0 newly installed, 0 to remove and 101 not upgraded.
Need to get 870 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcurl4-openssl-dev amd64 7.81.0-1ubuntu1.22 [386 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 curl amd64 7.81.0-1ubuntu1.22 [194 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcurl4 amd64 7.81.0-1ubuntu1.22 [290 kB]
Fetched 870 kB in 1s (779 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 3.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
(Reading database ... 117540 files and directories currently installed.)
Preparing to unpack .../libcurl4-openssl-dev_7.81.0-1ubuntu1.22_amd64.deb ...
Unpacking libcurl4-openssl-dev:amd64 (7.81.0-1ubuntu1.22) over (7.81.0-1ubuntu1.21) ...
Preparing to unpack .../curl_7.81.0-1ubuntu1.22_amd64.deb ...
Unpacking curl (7.81.0-1ubuntu1.22) over (7.81.0-1ubuntu1.21) ...
Preparing to unpack .../libcurl4_7.81.0-1ubuntu1.22_amd64.deb ...
Unpacking libcurl4:amd64 (7.81.0-1ubuntu1.22) over (7.81.0-1ubuntu1.21) ...
Setting up libcurl4:amd64 (7.81.0-1ubuntu1.22) ...
Setting up curl (7.81.0-1ubuntu1.22) ...
Setting up libcurl4-openssl-dev:amd64 (7.81.0-1ubuntu1.22) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.11) ...
/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main
Get:1 https://cli.github.com/packages stable InRelease [3,917 B]
Get:2 https://deb.nodesource.com/node_20.x nodistro InRelease [12.1 kB]
Hit:3 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:4 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:7 https://deb.nodesource.com/node_20.x nodistro/main amd64 Packages [13.8 kB]
Hit:8 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 29.9 kB in 1s (24.4 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  nodejs
0 upgraded, 1 newly installed, 0 to remove and 101 not upgraded.
Need to get 32.0 MB of archives.
After this operation, 197 MB of additional disk space will be used.
Get:1 https://deb.nodesource.com/node_20.x nodistro/main amd64 nodejs amd64 20.20.0-1nodesource1 [32.0 MB]
Fetched 32.0 MB in 1s (56.5 MB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 78, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package nodejs.
(Reading database ... 117540 files and directories currently installed.)
Preparing to unpack .../nodejs_20.20.0-1nodesource1_amd64.deb ...
Unpacking nodejs (20.20.0-1nodesource1) ...
Setting up nodejs (20.20.0-1nodesource1) ...
Processing triggers for man-db (2.10.2-1) ...
v20.20.0

In [4]:
!npx playwright install-deps

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙Need to install the following packages:
playwright@1.58.2
Ok to proceed? (y) y

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹Installing dependencies...
Get:1 https://cli.github.com/packages stable InRelease [3,917 B]
Hit:2 https://deb.nodesource.com/node_20.x nodistro InRelease
Hit:3 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:4 https://r2u.stat.illinois.edu/ubuntu jammy InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:6 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:7 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:9 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Fetched 3,917 B in 1s (3,002 B/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
fonts-liberation is already the newest version (1:1.07.4-11).
libcairo-gobject2 is already the newest version (1.16.0-5ubuntu2).
libcairo-gobject2 set to manually installed.
libcairo2 is already the newest version (1.16.0-5ubuntu2).
libcairo2 set to manually installed.
libegl1 is already the newest version (1.4.0-1).
libepoxy0 is already the newest version (1.5.10-1).
libepoxy0 set to manually installed.
libevent-2.1-7 is already the newest version (2.1.12-stable-1build3).
libevent-2.1-7 set to manually installed.
libfontconfig1 is already the newest version (2.13.1-4.2ubuntu5).
libgles2 is already the newest version (1.4.0-1).
libglx0 is already the newest version (1.4.0-1).
libglx0 set to manually installed.
libicu70 is already the newest version (70.1-2).
libicu70 set to manually installed.
libjpeg-turbo8 is already the newest version (2.1.2-0ubuntu1).
libjpeg-turbo8 set to manually installed.
liblcms2-2 is already the newest version (2.12~rc1-2build2).
liblcms2-2 set to manually installed.
libopengl0 is already the newest version (1.4.0-1).
libopus0 is already the newest version (1.3.1-0.1build2).
libopus0 set to manually installed.
libxcb-shm0 is already the newest version (1.14-3ubuntu3).
libxcb-shm0 set to manually installed.
libxcb1 is already the newest version (1.14-3ubuntu3).
libxcb1 set to manually installed.
libxcursor1 is already the newest version (1:1.2.0-2build4).
libxcursor1 set to manually installed.
libxdamage1 is already the newest version (1:1.1.5-2build2).
libxdamage1 set to manually installed.
libxext6 is already the newest version (2:1.3.4-1build1).
libxfixes3 is already the newest version (1:6.0.0-1).
libxfixes3 set to manually installed.
libxi6 is already the newest version (2:1.8-1build1).
libxi6 set to manually installed.
libxkbcommon0 is already the newest version (1.4.0-1).
libxkbcommon0 set to manually installed.
libxrandr2 is already the newest version (2:1.5.2-1build1).
libxrandr2 set to manually installed.
libxrender1 is already the newest version (1:0.9.10-1build4).
libx264-163 is already the newest version (2:0.163.3060+git5db6aa6-2build1).
libx264-163 set to manually installed.
libcups2 is already the newest version (2.4.1op1-1ubuntu4.16).
libcups2 set to manually installed.
libdbus-1-3 is already the newest version (1.12.20-2ubuntu4.1).
libdbus-1-3 set to manually installed.
libdrm2 is already the newest version (2.4.113-2~ubuntu0.22.04.1).
libdrm2 set to manually installed.
libfreetype6 is already the newest version (2.11.1+dfsg-1ubuntu0.3).
libfreetype6 set to manually installed.
libgbm1 is already the newest version (23.2.1-1ubuntu3.1~22.04.3).
libgbm1 set to manually installed.
libgdk-pixbuf-2.0-0 is already the newest version (2.42.8+dfsg-1ubuntu0.4).
libgdk-pixbuf-2.0-0 set to manually installed.
libgstreamer1.0-0 is already the newest version (1.20.3-0ubuntu1.1).
libgstreamer1.0-0 set to manually installed.
libgtk-4-1 is already the newest version (4.6.9+ds-0ubuntu0.22.04.2).
libgtk-4-1 set to manually installed.
libharfbuzz0b is already the newest version (2.7.4-1ubuntu3.2).
libharfbuzz0b set to manually installed.
libnspr4 is already the newest version (2:4.35-0ubuntu0.22.04.1).
libnspr4 set to manually installed.
libnss3 is already the newest version (2:3.98-0ubuntu0.22.04.2).
libnss3 set to manually installed.
libopenjp2-7 is already the newest version (2.4.0-6ubuntu0.4).
libopenjp2-7 set to manually installed.
libpango-1.0-0 is already the newest version (1.50.6+ds-2ubuntu1).
libpango-1.0-0 set to manually installed.
libpangocairo-1.0-0 is already the newest version (1.50.6+ds-2ubuntu1).
libpangocairo-1.0-0 set to manually installed.
libwayland-client0 is already the newest version (1.20.0-1ubuntu0.1).
libwayland-client0 set to manually installed.
libwayland-egl1 is already the newest version (1.20.0-1ubuntu0.1).
libwayland-egl1 set to manually installed.
libwayland-server0 is already the newest version (1.20.0-1ubuntu0.1).
libwayland-server0 set to manually installed.
libwebpdemux2 is already the newest version (1.2.2-2ubuntu0.22.04.2).
libx11-6 is already the newest version (2:1.7.5-1ubuntu0.3).
libx11-6 set to manually installed.
libx11-xcb1 is already the newest version (2:1.7.5-1ubuntu0.3).
libx11-xcb1 set to manually installed.
libxslt1.1 is already the newest version (1.1.34-4ubuntu0.22.04.5).
ffmpeg is already the newest version (7:4.4.2-0ubuntu0.22.04.1).
xvfb is already the newest version (2:21.1.4-2ubuntu1.7~22.04.16).
The following additional packages will be installed:
  dictionaries-common gcc-12-base glib-networking glib-networking-common
  glib-networking-services gsettings-desktop-schemas hunspell-en-us libaa1
  libabsl20210324 libasound2-data libaspell15 libatk1.0-data libcc1-0
  libcdparanoia0 libdca0 libdv4 libdvdnav4 libdvdread8 libfaad2 libfluidsynth3
  libfreeaptx0 libgav1-0 libgcc-s1 libgfortran5 libglib2.0-bin libglib2.0-dev
  libglib2.0-dev-bin libgomp1 libgssdp-1.2-0 libgstreamer-plugins-bad1.0-0
  libgstreamer-plugins-good1.0-0 libgtk-3-common libgupnp-1.2-1
  libgupnp-igd-1.0-4 libhunspell-1.7-0 libilmbase25 libinstpatch-1.0-2 libitm1
  libjson-glib-1.0-0 libjson-glib-1.0-common libkate1 libldacbt-enc2 liblsan0
  libltc11 libmjpegutils-2.1-0 libmodplug1 libmpcdec6 libmpeg2encpp-2.1-0
  libmplex2-2.1-0 libnice10 libopenexr25 libopenh264-6 libopenni2-0
  liborc-0.4-0 libpng-dev libqrencode4 libquadmath0 libsbc1 libsecret-common
  libshout3 libsoundtouch1 libsoup-3.0-common libsoup2.4-1 libsoup2.4-common
  libspandsp2 libsrtp2-1 libstdc++6 libtag1v5 libtag1v5-vanilla
  libtext-iconv-perl libubsan1 libv4l-0 libv4lconvert0 libvisual-0.4-0
  libvo-aacenc0 libvo-amrwbenc0 libwavpack1 libwebrtc-audio-processing1
  libwildmidi2 libxml2-dev libyuv0 libzbar0 libzxingcore1 session-migration
  timgm6mb-soundfont xfonts-encodings xfonts-utils
Suggested packages:
  ispell | aspell | hunspell wordlist frei0r-plugins gvfs hunspell
  openoffice.org-hunspell | openoffice.org-core libasound2-plugins alsa-utils
  aspell libdv-bin oss-compat libdvdcss2 libenchant-2-voikko libglib2.0-doc
  libgdk-pixbuf2.0-bin | libgdk-pixbuf2.0-dev libxml2-utils
  libvisual-0.4-plugins gnome-shell | notification-daemon libwildmidi-config
  fluid-soundfont-gm
Recommended packages:
  fonts-ipafont-mincho fonts-tlwg-loma gstreamer1.0-x alsa-ucm-conf
  alsa-topology-conf aspell-en | aspell-dictionary | aspell6a-dictionary
  at-spi2-core enchant-2 xdg-user-dirs gstreamer1.0-gl libgtk-3-bin
  librsvg2-common libpng-tools libmagickcore-6.q16-6-extra
The following NEW packages will be installed:
  dictionaries-common fonts-freefont-ttf fonts-ipafont-gothic
  fonts-noto-color-emoji fonts-tlwg-loma-otf fonts-unifont fonts-wqy-zenhei
  glib-networking glib-networking-common glib-networking-services
  gsettings-desktop-schemas gstreamer1.0-libav gstreamer1.0-plugins-bad
  gstreamer1.0-plugins-base gstreamer1.0-plugins-good hunspell-en-us libaa1
  libabsl20210324 libaspell15 libatk-bridge2.0-0 libatk1.0-0 libatk1.0-data
  libatspi2.0-0 libavif13 libcdparanoia0 libdbus-glib-1-2 libdca0 libdv4
  libdvdnav4 libdvdread8 libenchant-2-2 libevdev2 libfaad2 libffi7
  libfluidsynth3 libfreeaptx0 libgav1-0 libgssdp-1.2-0 libgstreamer-gl1.0-0
  libgstreamer-plugins-bad1.0-0 libgstreamer-plugins-base1.0-0
  libgstreamer-plugins-good1.0-0 libgtk-3-0 libgtk-3-common libgudev-1.0-0
  libgupnp-1.2-1 libgupnp-igd-1.0-4 libharfbuzz-icu0 libhunspell-1.7-0
  libhyphen0 libilmbase25 libinstpatch-1.0-2 libjson-glib-1.0-0
  libjson-glib-1.0-common libkate1 libldacbt-enc2 libltc11 libmanette-0.2-0
  libmjpegutils-2.1-0 libmodplug1 libmpcdec6 libmpeg2encpp-2.1-0
  libmplex2-2.1-0 libnice10 libnotify4 libopenexr25 libopenh264-6 libopenni2-0
  liborc-0.4-0 libproxy1v5 libqrencode4 libsbc1 libsecret-1-0 libsecret-common
  libshout3 libsoundtouch1 libsoup-3.0-0 libsoup-3.0-common libsoup2.4-1
  libsoup2.4-common libspandsp2 libsrtp2-1 libtag1v5 libtag1v5-vanilla
  libtext-iconv-perl libv4l-0 libv4lconvert0 libvisual-0.4-0 libvo-aacenc0
  libvo-amrwbenc0 libwavpack1 libwebrtc-audio-processing1 libwildmidi2
  libwoff1 libxcomposite1 libxtst6 libyuv0 libzbar0 libzxingcore1
  session-migration timgm6mb-soundfont xfonts-cyrillic xfonts-encodings
  xfonts-scalable xfonts-utils
The following packages will be upgraded:
  gcc-12-base libasound2 libasound2-data libatomic1 libcc1-0 libgcc-s1
  libgfortran5 libglib2.0-0 libglib2.0-bin libglib2.0-dev libglib2.0-dev-bin
  libgomp1 libitm1 liblsan0 libpng-dev libpng16-16 libquadmath0 libstdc++6
  libubsan1 libxml2 libxml2-dev
21 upgraded, 105 newly installed, 0 to remove and 80 not upgraded.
Need to get 63.7 MB of archives.
After this operation, 142 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-ipafont-gothic all 00303-21ubuntu1 [3,513 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libatomic1 amd64 12.3.0-1ubuntu1~22.04.3 [10.5 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libubsan1 amd64 12.3.0-1ubuntu1~22.04.3 [976 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 gcc-12-base amd64 12.3.0-1ubuntu1~22.04.3 [216 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libstdc++6 amd64 12.3.0-1ubuntu1~22.04.3 [699 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libquadmath0 amd64 12.3.0-1ubuntu1~22.04.3 [154 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 liblsan0 amd64 12.3.0-1ubuntu1~22.04.3 [1,069 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libitm1 amd64 12.3.0-1ubuntu1~22.04.3 [30.2 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgomp1 amd64 12.3.0-1ubuntu1~22.04.3 [127 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgfortran5 amd64 12.3.0-1ubuntu1~22.04.3 [879 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libcc1-0 amd64 12.3.0-1ubuntu1~22.04.3 [48.3 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgcc-s1 amd64 12.3.0-1ubuntu1~22.04.3 [53.9 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libglib2.0-dev amd64 2.72.4-0ubuntu2.9 [1,744 kB]
Get:14 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libglib2.0-dev-bin amd64 2.72.4-0ubuntu2.9 [117 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libglib2.0-bin amd64 2.72.4-0ubuntu2.9 [80.9 kB]
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libglib2.0-0 amd64 2.72.4-0ubuntu2.9 [1,467 kB]
Get:17 http://archive.ubuntu.com/ubuntu jammy/main amd64 libtext-iconv-perl amd64 1.7-7build3 [14.3 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libxml2-dev amd64 2.9.13+dfsg-1ubuntu0.11 [805 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libxml2 amd64 2.9.13+dfsg-1ubuntu0.11 [765 kB]
Get:20 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpng-dev amd64 1.6.37-3ubuntu0.4 [193 kB]
Get:21 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libpng16-16 amd64 1.6.37-3ubuntu0.4 [192 kB]
Get:22 http://archive.ubuntu.com/ubuntu jammy/main amd64 dictionaries-common all 1.28.14 [185 kB]
Get:23 http://archive.ubuntu.com/ubuntu jammy/main amd64 fonts-freefont-ttf all 20120503-10build1 [2,388 kB]
Get:24 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 fonts-noto-color-emoji all 2.047-0ubuntu0.22.04.1 [10.0 MB]
Get:25 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-tlwg-loma-otf all 1:0.7.3-1 [107 kB]
Get:26 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-unifont all 1:14.0.01-1 [3,551 kB]
Get:27 http://archive.ubuntu.com/ubuntu jammy/universe amd64 fonts-wqy-zenhei all 0.9.45-8 [7,472 kB]
Get:28 http://archive.ubuntu.com/ubuntu jammy/main amd64 libproxy1v5 amd64 0.4.17-2 [51.9 kB]
Get:29 http://archive.ubuntu.com/ubuntu jammy/main amd64 glib-networking-common all 2.72.0-1 [3,718 B]
Get:30 http://archive.ubuntu.com/ubuntu jammy/main amd64 glib-networking-services amd64 2.72.0-1 [9,982 B]
Get:31 http://archive.ubuntu.com/ubuntu jammy/main amd64 session-migration amd64 0.3.6 [9,774 B]
Get:32 http://archive.ubuntu.com/ubuntu jammy/main amd64 gsettings-desktop-schemas all 42.0-1ubuntu1 [31.1 kB]
Get:33 http://archive.ubuntu.com/ubuntu jammy/main amd64 glib-networking amd64 2.72.0-1 [69.8 kB]
Get:34 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 liborc-0.4-0 amd64 1:0.4.32-2ubuntu0.1 [228 kB]
Get:35 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgstreamer-plugins-base1.0-0 amd64 1.20.1-1ubuntu0.5 [848 kB]
Get:36 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 gstreamer1.0-libav amd64 1.20.3-0ubuntu1 [103 kB]
Get:37 http://archive.ubuntu.com/ubuntu jammy/main amd64 libcdparanoia0 amd64 3.10.2+debian-14build2 [49.3 kB]
Get:38 http://archive.ubuntu.com/ubuntu jammy/main amd64 libvisual-0.4-0 amd64 0.4.0-17build2 [108 kB]
Get:39 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 gstreamer1.0-plugins-base amd64 1.20.1-1ubuntu0.5 [712 kB]
Get:40 http://archive.ubuntu.com/ubuntu jammy/main amd64 libaa1 amd64 1.4p5-50build1 [51.9 kB]
Get:41 http://archive.ubuntu.com/ubuntu jammy/main amd64 libdv4 amd64 1.0.0-14build1 [61.9 kB]
Get:42 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgstreamer-plugins-good1.0-0 amd64 1.20.3-0ubuntu1.4 [30.2 kB]
Get:43 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgudev-1.0-0 amd64 1:237-2build1 [16.3 kB]
Get:44 http://archive.ubuntu.com/ubuntu jammy/main amd64 libshout3 amd64 2.4.5-1build3 [54.5 kB]
Get:45 http://archive.ubuntu.com/ubuntu jammy/main amd64 libtag1v5-vanilla amd64 1.11.1+dfsg.1-3ubuntu3 [304 kB]
Get:46 http://archive.ubuntu.com/ubuntu jammy/main amd64 libtag1v5 amd64 1.11.1+dfsg.1-3ubuntu3 [11.5 kB]
Get:47 http://archive.ubuntu.com/ubuntu jammy/main amd64 libv4lconvert0 amd64 1.22.1-2build1 [82.4 kB]
Get:48 http://archive.ubuntu.com/ubuntu jammy/main amd64 libv4l-0 amd64 1.22.1-2build1 [44.9 kB]
Get:49 http://archive.ubuntu.com/ubuntu jammy/main amd64 libwavpack1 amd64 5.4.0-1build2 [83.7 kB]
Get:50 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libsoup2.4-common all 2.74.2-3ubuntu0.6 [4,778 B]
Get:51 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libsoup2.4-1 amd64 2.74.2-3ubuntu0.6 [288 kB]
Get:52 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 gstreamer1.0-plugins-good amd64 1.20.3-0ubuntu1.4 [2,009 kB]
Get:53 http://archive.ubuntu.com/ubuntu jammy/main amd64 hunspell-en-us all 1:2020.12.07-2 [280 kB]
Get:54 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libabsl20210324 amd64 0~20210324.2-2ubuntu0.3 [386 kB]
Get:55 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libasound2 amd64 1.2.6.1-1ubuntu1.1 [391 kB]
Get:56 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libasound2-data all 1.2.6.1-1ubuntu1.1 [19.3 kB]
Get:57 http://archive.ubuntu.com/ubuntu jammy/main amd64 libaspell15 amd64 0.60.8-4build1 [325 kB]
Get:58 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-data all 2.36.0-3build1 [2,824 B]
Get:59 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-0 amd64 2.36.0-3build1 [51.9 kB]
Get:60 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatspi2.0-0 amd64 2.44.0-3 [80.9 kB]
Get:61 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-bridge2.0-0 amd64 2.38.0-3 [66.6 kB]
Get:62 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libgav1-0 amd64 0.17.0-1build1 [336 kB]
Get:63 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libyuv0 amd64 0.0~git20220104.b91df1a-2 [154 kB]
Get:64 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libavif13 amd64 0.9.3-3 [69.5 kB]
Get:65 http://archive.ubuntu.com/ubuntu jammy/main amd64 libdbus-glib-1-2 amd64 0.112-2build1 [65.4 kB]
Get:66 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libdvdread8 amd64 6.1.2-1 [55.7 kB]
Get:67 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libdvdnav4 amd64 6.1.1-1 [39.3 kB]
Get:68 http://archive.ubuntu.com/ubuntu jammy/main amd64 libhunspell-1.7-0 amd64 1.7.0-4build1 [175 kB]
Get:69 http://archive.ubuntu.com/ubuntu jammy/main amd64 libenchant-2-2 amd64 2.3.2-1ubuntu2 [50.9 kB]
Get:70 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libfaad2 amd64 2.10.0-2 [197 kB]
Get:71 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libffi7 amd64 3.3-5ubuntu1 [19.9 kB]
Get:72 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libinstpatch-1.0-2 amd64 1.1.6-1 [240 kB]
Get:73 http://archive.ubuntu.com/ubuntu jammy/universe amd64 timgm6mb-soundfont all 1.3-5 [5,427 kB]
Get:74 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libfluidsynth3 amd64 2.2.5-1 [246 kB]
Get:75 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libfreeaptx0 amd64 0.1.1-1 [12.9 kB]
Get:76 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgssdp-1.2-0 amd64 1.4.0.1-2build1 [48.9 kB]
Get:77 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgstreamer-gl1.0-0 amd64 1.20.1-1ubuntu0.5 [204 kB]
Get:78 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcomposite1 amd64 1:0.4.5-1build2 [7,192 B]
Get:79 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgtk-3-common all 3.24.33-1ubuntu2.2 [239 kB]
Get:80 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgtk-3-0 amd64 3.24.33-1ubuntu2.2 [3,053 kB]
Get:81 http://archive.ubuntu.com/ubuntu jammy/main amd64 libgupnp-1.2-1 amd64 1.4.3-1 [93.3 kB]
Get:82 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libgupnp-igd-1.0-4 amd64 1.2.0-1build1 [16.8 kB]
Get:83 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libharfbuzz-icu0 amd64 2.7.4-1ubuntu3.2 [5,890 B]
Get:84 http://archive.ubuntu.com/ubuntu jammy/main amd64 libhyphen0 amd64 2.8.8-7build2 [28.2 kB]
Get:85 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libilmbase25 amd64 2.5.7-2 [175 kB]
Get:86 http://archive.ubuntu.com/ubuntu jammy/main amd64 libjson-glib-1.0-common all 1.6.6-1build1 [4,432 B]
Get:87 http://archive.ubuntu.com/ubuntu jammy/main amd64 libjson-glib-1.0-0 amd64 1.6.6-1build1 [69.9 kB]
Get:88 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libkate1 amd64 0.4.1-11build1 [39.4 kB]
Get:89 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libldacbt-enc2 amd64 2.0.2.3+git20200429+ed310a0-4 [24.6 kB]
Get:90 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libltc11 amd64 1.3.1-1 [12.3 kB]
Get:91 http://archive.ubuntu.com/ubuntu jammy/main amd64 libevdev2 amd64 1.12.1+dfsg-1 [39.5 kB]
Get:92 http://archive.ubuntu.com/ubuntu jammy/main amd64 libmanette-0.2-0 amd64 0.2.6-3build1 [30.4 kB]
Get:93 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libmjpegutils-2.1-0 amd64 1:2.1.0+debian-6build1 [24.1 kB]
Get:94 http://archive.ubuntu.com/ubuntu jammy/universe amd64 libmodplug1 amd64 1:0.8.9.0-3 [153 kB]

In [45]:
# Crawl Data

filename = 'lpdp_februari_2026_39.csv'
search_keyword = 'lpdp since:2026-02-21 until:2026-02-22'

limit = 5000

!npx -y tweet-harvest@2.6.1 -o "{filename}" -s "{search_keyword}" --tab "LATEST" -l {limit} --token {twitter_auth_token}

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


Found existing file ./tweets-data/lpdp_februari_2026_39.csv, renaming to ./tweets-data/lpdp_februari_2026_39.old.csv

-- Scrolling... (1) (2) (3)
Filling in keywords: lpdp since:2026-02-21 until:2026-02-22

 (4) (5) (6)

Your tweets saved to: /content/tweets-data/lpdp_februari_2026_39.csv
Total tweets saved: 18


Your tweets saved to: /content/tweets-data/lpdp_februari_2026_39.csv
Total tweets saved: 36

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/lpdp_februari_2026_39.csv
Total tweets saved: 54

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 54 tweets, done scrolling...
⠙

In [46]:
import pandas as pd


file_path = f"tweets-data/{filename}"


df = pd.read_csv(file_path, delimiter=",")


display(df)

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,2025359595435425863,Sat Feb 21 23:59:01 +0000 2026,0,Hal ini yang membuat saya berjuang mencari car...,2025359636380221855,NaN,_dumpingmind,in,NaN,0,1,0,https://x.com/undefined/status/202535963638022...,1494530045158776840,NaN
1,2025359595435425863,Sat Feb 21 23:58:58 +0000 2026,0,Hati saya tidak mengijinkan krn sedari awal sa...,2025359624124453070,NaN,_dumpingmind,in,NaN,0,1,0,https://x.com/undefined/status/202535962412445...,1494530045158776840,NaN
2,2025359595435425863,Sat Feb 21 23:58:57 +0000 2026,0,Tentu saja saya pernah mempertimbangkan LPDP k...,2025359619703582800,NaN,_dumpingmind,in,NaN,0,1,0,https://x.com/undefined/status/202535961970358...,1494530045158776840,NaN
3,2025359360818552841,Sat Feb 21 23:57:55 +0000 2026,0,my partner's family is also well-off but one t...,2025359360818552841,NaN,NaN,en,NaN,0,1,0,https://x.com/undefined/status/202535936081855...,1550881431613648898,NaN
4,2025058603322016123,Sat Feb 21 23:54:09 +0000 2026,2,@narkosun Sebaiknya @LPDP_RI mencabut program ...,2025358410980753739,NaN,narkosun,in,NaN,0,0,0,https://x.com/undefined/status/202535841098075...,112104043,NaN
5,2025358273285947554,Sat Feb 21 23:53:36 +0000 2026,9,SLOT GACOR HARI INI Tenang main jangan gegaba...,2025358273285947554,https://pbs.twimg.com/media/HBuElTmbgAAGYdz.png,NaN,in,NaN,0,0,3,https://x.com/undefined/status/202535827328594...,2003081503669198850,NaN
6,2025358211902210076,Sat Feb 21 23:53:21 +0000 2026,1,Pake LPDP (duit rakyat indo) Udah sampe sana p...,2025358211902210076,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202535821190221...,1369825704142020609,NaN
7,2025357814278094945,Sat Feb 21 23:51:46 +0000 2026,8,Emang paling anj- namanya berak abis sahur ️ _...,2025357814278094945,https://pbs.twimg.com/media/HBuEMXxakAAid-k.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202535781427809...,4142411112,NaN
8,2025051440222490782,Sat Feb 21 23:51:33 +0000 2026,0,@Dedy44169434 @agitaap2 @narkosun Negara punya...,2025357755998208130,NaN,Dedy44169434,in,NaN,0,0,0,https://x.com/undefined/status/202535775599820...,261061949,NaN
9,2024970522212401641,Sat Feb 21 23:49:35 +0000 2026,0,@HukumDan @ListyoSigitP Mayoritas siswa begaju...,2025357264237068768,NaN,HukumDan,in,NaN,0,0,0,https://x.com/undefined/status/202535726423706...,958930112916766725,NaN
10,2024869840666968211,Sat Feb 21 23:48:58 +0000 2026,0,@louisvuittyong @LPDP_RI Asli ini jelas jelas ...,2025357106208276955,NaN,louisvuittyong,in,NaN,0,0,0,https://x.com/undefined/status/202535710620827...,73557809,NaN
11,2025096892619915278,Sat Feb 21 23:48:29 +0000 2026,1,@Uzzzzz222 Barisan sakit hati rupanya. Udah ke...,2025356987924721874,NaN,Uzzzzz222,in,NaN,0,0,0,https://x.com/undefined/status/202535698792472...,1925081813774700544,NaN
12,2025058603322016123,Sat Feb 21 23:47:48 +0000 2026,0,@narkosun Anaknya mau kewarganegaraan mana itu...,2025356814637060305,NaN,narkosun,in,NaN,0,0,0,https://x.com/undefined/status/202535681463706...,800501982251229184,NaN
13,2024991503945547777,Sat Feb 21 23:47:07 +0000 2026,0,@Palangkan7 @snowflakemlet Yng dipermasalahkan...,2025356644096639455,NaN,Palangkan7,in,NaN,0,1,0,https://x.com/undefined/status/202535664409663...,1947473136758493185,NaN
14,2024991503945547777,Sat Feb 21 23:44:58 +0000 2026,0,@Palangkan7 @ysayeballade @snowflakemlet Orang...,2025356099957010704,NaN,Palangkan7,in,NaN,0,1,0,https://x.com/undefined/status/202535609995701...,1999728174763245569,NaN
15,2024869840666968211,Sat Feb 21 23:44:32 +0000 2026,0,@LPDP_RI Paling benar memang banyakin penerima...,2025355992268161116,NaN,LPDP_RI,in,NaN,0,0,0,https://x.com/undefined/status/202535599226816...,73557809,NaN
16,2025051440222490782,Sat Feb 21 23:43:06 +0000 2026,0,@narkosun Padahal kutengkk2 ni si saset keknya...,2025355630756954132,NaN,narkosun,in,NaN,0,0,0,https://x.com/undefined/status/202535563075695...,1512790187449135106,NaN
17,2024861758511526216,Sat Feb 21 23:41:58 +0000 2026,0,@mas_veel stop LPDP bagi WN yg a nasionalis......,2025355347146539230,NaN,mas_veel,in,NaN,0,0,0,https://x.com/undefined/status/202535534714653...,3227019420,NaN
18,2025359595435425863,Sat Feb 21 23:59:01 +0000 2026,0,Hal ini yang membuat saya berjuang mencari car...,2025359636380221855,NaN,_dumpingmind,in,NaN,0,1,0,https://x.com/undefined/status/202535963638022...,1494530045158776840,NaN
19,2025359595435425863,Sat Feb 21 23:58:58 +0000 2026,0,Hati saya tidak mengijinkan krn sedari awal sa...,2025359624124453070,NaN,_dumpingmind,in,NaN,0,1,0,https://x.com/undefined/status/202535962412445...,1494530045158776840,NaN
20,2025359595435425863,Sat Feb 21 23:58:57 +0000 2026,0,Tentu saja saya pernah mempertimbangkan LPDP k...,2025359619703582800,NaN,_dumpingmind,in,NaN,0,1,0,https://x.com/undefined/status/202535961970358...,1494530045158776840,NaN
21,2025359360818552841,Sat Feb 21 23:57:55 +0000 2026,0,my partner's family is also well-off but one t...,2025359360818552841,NaN,NaN,en,NaN,0,1,0,https://x.com/undefined/status/202535936081855...,1550881431613648898,NaN
22,2025058603322016123,Sat Feb 21 23:54:09 +0000 2026,2,@narkosun Sebaiknya @LPDP_RI mencabut program ...,2025358410980753739,NaN,narkosun,in,NaN,0,0,0,https://x.com/undefined/status/202535841098075...,112104043,NaN
23,2025358273285947554,Sat Feb 21 23:53:36 +0000 2026,9,SLOT GACOR HARI INI Tenang main jangan gegaba...,2025358273285947554,https://pbs.twimg.com/media/HBuElTmbgAAGYdz.png,NaN,in,NaN,0,0,3,https://x.com/undefined/status/202535827328594...,2003081503669198850,NaN
24,2025358211902210076,Sat Feb 21 23:53:21 +0000 2026,1,Pake LPDP (duit rakyat indo) Udah sampe sana p...,2025358211902210076,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202535821190221...,1369825704142020609,NaN
25,2025357814278094945,Sat Feb 21 23:51:46 +0000 2026,8,Emang paling anj- namanya berak abis sahur ️ _...,2025357814278094945,https://pbs.twimg.com/media/HBuEMXxakAAid-k.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202535781427809...,4142411112,NaN
26,2025051440222490782,Sat Feb 21 23:51:33 +0000 2026,0,@Dedy44169434 @agitaap2 @narkosun Negara punya...,2025357755998208130,NaN,Dedy44169434,in,NaN,0,0,0,https://x.com/undefined/status/202535775599820...,261061949,NaN
27,2024970522212401641,Sat Feb 21 23:49:35 +0000 2026,0,@HukumDan @ListyoSigitP Mayoritas siswa begaju...,2025357264237068768,NaN,HukumDan,in,NaN,0,0,0,https://x.com/undefined/status/202535726423706...,958930112916766725,NaN
28,2024869840666968211,Sat Feb 21 23:48:58 +0000 2026,0,@louisvuittyong @LPDP_RI Asli ini jelas jelas ...,2025357106208276955,NaN,louisvuittyong,in,NaN,0,0,0,https://x.com/undefined/status/202535710620827...,73557809,NaN
29,2025096892619915278,Sat Feb 21 23:48:29 +0000 2026,1,@Uzzzzz222 Barisan sakit hati rupanya. Udah ke...,2025356987924721874,NaN,Uzzzzz222,in,NaN,0,0,0,https://x.com/undefined/status/202535698792472...,1925081813774700544,NaN
30,2025058603322016123,Sat Feb 21 23:47:48 +0000 2026,0,@narkosun Anaknya mau kewarganegaraan mana itu...,2025356814637060305,NaN,narkosun,in,NaN,0,0,0,https://x.com/undefined/status/202535681463706...,800501982251229184,NaN
31,2024991503945547777,Sat Feb 21 23:47:07 +0000 2026,0,@Palangkan7 @snowflakemlet Yng dipermasalahkan...,2025356644096639455,NaN,Palangkan7,in,NaN,0,1,0,https://x.com/undefined/status/202535664409663...,1947473136758493185,NaN
32,2024991503945547777,Sat Feb 21 23:44:58 +0000 2026,0,@Palangkan7 @ysayeballade @snowflakemlet Orang...,2025356099957010704,NaN,Palangkan7,in,NaN,0,1,0,https://x.com/undefined/status/202535609995701...,1999728174763245569,NaN
33,2024869840666968211,Sat Feb 21 23:44:32 +0000 2026,0,@LPDP_RI Paling benar memang banyakin penerima...,2025355992268161116,NaN,LPDP_RI,in,NaN,0,0,0,https://x.com/undefined/status/202535599226816...,73557809,NaN
34,2025051440222490782,Sat Feb 21 23:43:06 +0000 2026,0,@narkosun Padahal kutengkk2 ni si saset keknya...,2025355630756954132,NaN,narkosun,in,NaN,0,0,0,https://x.com/undefined/status/202535563075695...,1512790187449135106,NaN
35,2024861758511526216,Sat Feb 21 23:41:58 +0000 2026,0,@mas_veel stop LPDP bagi WN yg a nasionalis......,2025355347146539230,NaN,mas_veel,in,NaN,0,0,0,https://x.com/undefined/status/202535534714653...,3227019420,NaN
36,2025359595435425863,Sat Feb 21 23:59:01 +0000 2026,0,Hal ini yang membuat saya berjuang mencari car...,2025359636380221855,NaN,_dumpingmind,in,NaN,0,1,0,https://x.com/undefined/status/202535963638022...,1494530045158776840,NaN
37,2025359595435425863,Sat Feb 21 23:58:58 +0000 2026,0,Hati saya tidak mengijinkan krn sedari awal sa...,2025359624124453070,NaN,_dumpingmind,in,NaN,0,1,0,https://x.com/undefined/status/202535962412445...,1494530045158776840,NaN
38,2025359595435425863,Sat Feb 21 23:58:57 +0000 2026,0,Tentu saja saya pernah mempertimbangkan LPDP k...,2025359619703582800,NaN,_dumpingmind,in,NaN,0,1,0,https://x.com/undefined/status/202535961970358...,1494530045158776840,NaN
39,2025359360818552841,Sat Feb 21 23:57:55 +0000 2026,0,my partner's family is also well-off but one t...,2025359360818552841,NaN,NaN,en,NaN,0,1,0,https://x.com/undefined/status/202535936081855...,1550881431613648898,NaN
40,2025058603322016123,Sat Feb 21 23:54:09 +0000 2026,2,@narkosun Sebaiknya @LPDP_RI mencabut program ...,2025358410980753739,NaN,narkosun,in,NaN,0,0,0,https://x.com/undefined/status/202535841098075...,112104043,NaN
41,2025358273285947554,Sat Feb 21 23:53:36 +0000 2026,9,SLOT GACOR HARI INI Tenang main jangan gegaba...,2025358273285947554,https://pbs.twimg.com/media/HBuElTmbgAAGYdz.png,NaN,in,NaN,0,0,3,https://x.com/undefined/status/202535827328594...,2003081503669198850,NaN
42,2025358211902210076,Sat Feb 21 23:53:21 +0000 2026,1,Pake LPDP (duit rakyat indo) Udah sampe sana p...,2025358211902210076,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202535821190221...,1369825704142020609,NaN
43,2025357814278094945,Sat Feb 21 23:51:46 +0000 2026,8,Emang paling anj- namanya berak abis sahur ️ _...,2025357814278094945,https://pbs.twimg.com/media/HBuEMXxakAAid-k.jpg,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202535781427809...,4142411112,NaN
44,2025051440222490782,Sat Feb 21 23:51:33 +0000 2026,0,@Dedy44169434 @agitaap2 @narkosun Negara punya...,2025357755998208130,NaN,Dedy44169434,in,NaN,0,0,0,https://x.com/undefined/status/202535775599820...,261061949,NaN
45,2024970522212401641,Sat Feb 21 23:49:35 +0000 2026,0,@HukumDan @ListyoSigitP Mayoritas siswa begaju...,2025357264237068768,NaN,HukumDan,in,NaN,0,0,0,https://x.com/undefined/status/202535726423706...,958930112916766725,NaN
46,2024869840666968211,Sat Feb 21 23:48:58 +0000 2026,0,@louisvuittyong @LPDP_RI Asli ini jelas jelas ...,2025357106208276955,NaN,louisvuittyong,in,NaN,0,0,0,https://x.com/undefined/status/202535710620827...,73557809,NaN
47,2025096892619915278,Sat Feb 21 23:48:29 +0000 2026,1,@Uzzzzz222 Barisan sakit hati rupanya. Udah ke...,2025356987924721874,NaN,Uzzzzz222,in,NaN,0,0,0,https://x.com/undefined/status/202535698792472...,1925081813774700544,NaN
48,2025058603322016123,Sat Feb 21 23:47:48 +0000 2026,0,@narkosun Anaknya mau kewarganegaraan mana itu...,2025356814637060305,NaN,narkosun,in,NaN,0,0,0,https://x.com/undefined/status/202535681463706...,800501982251229184,NaN
49,2024991503945547777,Sat Feb 21 23:47:07 +0000 2026,0,@Palangkan7 @snowflakemlet Yng dipermasalahkan...,2025356644096639455,NaN,Palangkan7,in,NaN,0,1,0,https://x.com/undefined/status/202535664409663...,1947473136758493185,NaN
50,2024991503945547777,Sat Feb 21 23:44:58 +0000 2026,0,@Palangkan7 @ysayeballade @snowflakemlet Orang...,2025356099957010704,NaN,Palangkan7,in,NaN,0,1,0,https://x.com/undefined/status/202535609995701...,1999728174763245569,NaN
51,2024869840666968211,Sat Feb 21 23:44:32 +0000 2026,0,@LPDP_RI Paling benar memang banyakin penerima...,2025355992268161116,NaN,LPDP_RI,in,NaN,0,0,0,https://x.com/undefined/status/202535599226816...,73557809,NaN
52,2025051440222490782,Sat Feb 21 23:43:06 +0000 2026,0,@narkosun Padahal kutengkk2 ni si saset keknya...,2025355630756954132,NaN,narkosun,in,NaN,0,0,0,https://x.com/undefined/status/202535563075695...,1512790187449135106,NaN
53,2024861758511526216,Sat Feb 21 23:41:58 +0000 2026,0,@mas_veel stop LPDP bagi WN yg a nasionalis......,2025355347146539230,NaN,mas_veel,in,NaN,0,0,0,https://x.com/undefined/status/202535534714653...,3227019420,NaN

In [47]:
df.to_csv('/content/drive/MyDrive/Int Conference/Hasil Crawling//lpdp_februari_2026_39.csv', index=False)

In [30]:
# Crawl Data

filename = 'lpdp_februari_2026_37.csv'
search_keyword = 'lpdp since:2026-02-19 until:2026-02-20'

limit = 5000

!npx -y tweet-harvest@2.6.1 -o "{filename}" -s "{search_keyword}" --tab "LATEST" -l {limit} --token {twitter_auth_token}

⠙⠹⠸⠼⠴⠦⠧⠇⠏Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2) (3) (4)
Filling in keywords: lpdp since:2026-02-19 until:2026-02-20

[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@75725f2bfa8ac2a16a1387df89f8005c"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@21a2a2df5d129558a9b940d59bfc80cf"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@fa06d6eb1a2d1030e693b25f8c06067b"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@042813996bd3b20cdaa1d78574f4baa0"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@e0192ab45f11df8788f336ea94f60272"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@d5cce1a3c5cab1b1f08c61d2ec24e29a"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@ef39f5d0dcd780ec713712a3b19cf98c"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.
[v2.6.1] Error parsing response json: {"_type":"Response","_guid":"response@d97c92cd509380f9c370ec4b6c41808b"}
[v2.6.1] Most likely, you have already exceeded the Twitter rate limit. Read more on https://x.com/elonmusk/status/1675187969420828672.


Your tweets saved to: /content/tweets-data/lpdp_februari_2026_37.csv
Total tweets saved: 17

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/lpdp_februari_2026_37.csv
Total tweets saved: 34

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result

-- Scrolling... (1)

Your tweets saved to: /content/tweets-data/lpdp_februari_2026_37.csv
Total tweets saved: 51

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1) (2)

Your tweets saved to: /content/tweets-data/lpdp_februari_2026_37.csv
Total tweets saved: 68

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...
[v2.6.1] No more tweets found, please check your search criteria and csv file result


Your tweets saved to: /content/tweets-data/lpdp_februari_2026_37.csv
Total tweets saved: 85


Your tweets saved to: /content/tweets-data/lpdp_februari_2026_37.csv
Total tweets saved: 102

--Taking a break, waiting for 10 seconds...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 102 tweets, done scrolling...
⠙

In [31]:
import pandas as pd


file_path = f"tweets-data/{filename}"


df = pd.read_csv(file_path, delimiter=",")


display(df)

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,2024518520831443163,Thu Feb 19 23:59:41 +0000 2026,1,@Jeffrekando @ardisatriawan @tomlembong gak us...,2024635029331333448,NaN,Jeffrekando,in,NaN,0,0,0,https://x.com/undefined/status/202463502933133...,44321053,NaN
1,2024635015490060785,Thu Feb 19 23:59:38 +0000 2026,0,Ribut lpdp yg diserang individu padahal sistem...,2024635015490060785,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202463501549006...,1639779970615771137,NaN
2,2024634985324613872,Thu Feb 19 23:59:31 +0000 2026,0,Ada benarnya juga karena kuliah di luar negeri...,2024634985324613872,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202463498532461...,1963812115581698048,NaN
3,2024634493001404682,Thu Feb 19 23:57:33 +0000 2026,0,https://t.co/vmvcDjUH5n https://t.co/k5sq1VBYK...,2024634493001404682,NaN,NaN,zxx,NaN,0,0,0,https://x.com/undefined/status/202463449300140...,2457865570,NaN
4,2024320980198576170,Thu Feb 19 23:57:14 +0000 2026,1,@wbspagi @tekarok007 Iya yah lagian yg alumni ...,2024634414328926565,NaN,wbspagi,in,NaN,0,1,0,https://x.com/undefined/status/202463441432892...,1846245356356751361,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,2024632413931131362,Thu Feb 19 23:49:17 +0000 2026,0,https://t.co/UvGDOBSOGt #DareYouToDeathEP9 #Ra...,2024632413931131362,NaN,NaN,qme,NaN,0,0,0,https://x.com/undefined/status/202463241393113...,1853844295075471360,NaN
98,2024631864934453609,Thu Feb 19 23:47:07 +0000 2026,32,Penampakan saat kapal melintas di jembatan Vel...,2024631864934453609,https://pbs.twimg.com/ext_tw_video_thumb/20246...,NaN,in,NaN,0,16,11,https://x.com/undefined/status/202463186493445...,1611654278862766080,NaN
99,2024631526307352616,Thu Feb 19 23:45:46 +0000 2026,0,Emg penerima lpdp tuh harus disaring lagi ya k...,2024631526307352616,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202463152630735...,1494324873602412548,NaN
100,2024630730396225858,Thu Feb 19 23:42:36 +0000 2026,912,Setiap rame rame LPDP artinya LPDP lagi open r...,2024630730396225858,https://pbs.twimg.com/media/HBju6vrbUAIP2rp.jpg,NaN,in,NaN,21,17,81,https://x.com/undefined/status/202463073039622...,501800437,NaN
101,2024411655342608592,Thu Feb 19 23:41:39 +0000 2026,0,@littlewomens3 Mau nanya: LPDP itu khusus WNI ...,2024630492759544013,NaN,littlewomens3,in,NaN,0,1,0,https://x.com/undefined/status/202463049275954...,564450110,NaN

In [32]:
df.to_csv('/content/drive/MyDrive/Int Conference/Hasil Crawling//lpdp_februari_2026_37.csv', index=False)

In [24]:
# Crawl Data

filename = 'lpdp_februari_2026_35.csv'
search_keyword = 'lpdp since:2026-02-16 until:2026-02-17'

limit = 5000

!npx -y tweet-harvest@2.6.1 -o "{filename}" -s "{search_keyword}" --tab "LATEST" -l {limit} --token {twitter_auth_token}

⠙⠹⠸⠼⠴⠦⠧Tweet Harvest [v2.6.1]

Research by Helmi Satria
Use it for Educational Purposes only!

This script uses Chromium Browser to crawl data from Twitter with your Twitter auth token.
Please enter your Twitter auth token when prompted.

Note: Keep your access token secret! Don't share it with anyone else.
Note: This script only runs on your local device.


Opening twitter search page...


-- Scrolling... (1) (2)
Filling in keywords: lpdp since:2026-02-16 until:2026-02-17

 (3) (4)

Your tweets saved to: /content/tweets-data/lpdp_februari_2026_35.csv
Total tweets saved: 19

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 1 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 2 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20) (21)No more tweets found, please check your search criteria and csv file result
Timeout reached 3 times, making sure again...

-- Scrolling... (1) (2) (3) (4) (5) (6) (7) (8) (9) (10) (11) (12) (13) (14) (15) (16) (17) (18) (19) (20)Got 19 tweets, done scrolling...
⠙

In [25]:
import pandas as pd


file_path = f"tweets-data/{filename}"


df = pd.read_csv(file_path, delimiter=",")


display(df)

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,2023340345388658712,Mon Feb 16 23:59:36 +0000 2026,32,@O5Bravo LPDP mendingan khusus Dosen atau PNS ...,2023547842724589789,NaN,O5Bravo,in,NaN,0,1,1,https://x.com/undefined/status/202354784272458...,1651228477524172802,NaN
1,2023340345388658712,Mon Feb 16 23:59:17 +0000 2026,0,@O5Bravo Gw lebih malu dan najis lu gunain kat...,2023547764890808353,NaN,O5Bravo,in,NaN,0,0,0,https://x.com/undefined/status/202354776489080...,1419161110930870275,NaN
2,2023291159607644336,Mon Feb 16 23:58:55 +0000 2026,0,@exxxtrahottt @ingingudluking @mownohoes @neoh...,2023547670711988431,NaN,exxxtrahottt,in,NaN,0,0,0,https://x.com/undefined/status/202354767071198...,1933969398701944832,NaN
3,2023348937391005859,Mon Feb 16 23:53:25 +0000 2026,0,@Ogaman888 Kalo memang bener ada bukti LPDP bu...,2023546289762513315,NaN,Ogaman888,in,NaN,0,2,0,https://x.com/undefined/status/202354628976251...,2704218780,NaN
4,2023340345388658712,Mon Feb 16 23:52:58 +0000 2026,5,@KejoraLoka @O5Bravo sorry kak just mau nanya ...,2023546175073480910,NaN,KejoraLoka,in,NaN,0,2,0,https://x.com/undefined/status/202354617507348...,1492804723531218946,NaN
5,2023420527231287775,Mon Feb 16 23:52:33 +0000 2026,5,@FrancDiAmante Tpi karena ada beberapa lpdp ke...,2023546071621005511,NaN,FrancDiAmante,in,NaN,0,0,0,https://x.com/undefined/status/202354607162100...,1920536087765921792,NaN
6,2023340345388658712,Mon Feb 16 23:47:22 +0000 2026,0,@ZmbyFrm @O5Bravo @roccoracoo73886 Ya jangan p...,2023544767167303965,NaN,ZmbyFrm,in,NaN,0,0,0,https://x.com/undefined/status/202354476716730...,1887738122198536192,NaN
7,2023544428783411456,Mon Feb 16 23:46:02 +0000 2026,1,Oh si sustainable gurl itu LPDP. Wkwkwkwk,2023544428783411456,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202354442878341...,68736463,NaN
8,2023340345388658712,Mon Feb 16 23:45:12 +0000 2026,0,@KeurCobain @ccmlyneu @travelmorethan @ayamgep...,2023544221786071443,NaN,KeurCobain,in,NaN,0,0,0,https://x.com/undefined/status/202354422178607...,1887738122198536192,NaN
9,2023340345388658712,Mon Feb 16 23:42:25 +0000 2026,1,@O5Bravo @jakiiyyuu @Reggga__ Dah dijawabin sm...,2023543519944863961,NaN,O5Bravo,in,NaN,0,0,0,https://x.com/undefined/status/202354351994486...,1705135864479969280,NaN
10,2023543087847665929,Mon Feb 16 23:40:42 +0000 2026,0,2025 msh afa aja orng ngerengek soal lpdp dan ...,2023543087847665929,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/202354308784766...,1705135864479969280,NaN
11,2023340345388658712,Mon Feb 16 23:39:02 +0000 2026,0,@mariomboys @O5Bravo @roccoracoo73886 Duit LPD...,2023542670359151022,NaN,mariomboys,in,NaN,0,2,0,https://x.com/undefined/status/202354267035915...,1887738122198536192,NaN
12,2023340345388658712,Mon Feb 16 23:38:49 +0000 2026,3,@ayah_ray_nay @O5Bravo 1. Mbak ini LPDP STEM (...,2023542616055574761,NaN,ayah_ray_nay,in,NaN,0,0,0,https://x.com/undefined/status/202354261605557...,1868140059989561344,NaN
13,2023538405251113348,Mon Feb 16 23:38:23 +0000 2026,0,Atau kritik knp pemerintah malah kasih gaji ke...,2023542506491965853,NaN,wahanakoa,in,NaN,0,0,0,https://x.com/undefined/status/202354250649196...,1705036648537640960,NaN
14,2023340345388658712,Mon Feb 16 23:36:07 +0000 2026,0,@O5Bravo ngapain malu ngejelekin negara korup ...,2023541934573437370,NaN,O5Bravo,in,NaN,0,0,0,https://x.com/undefined/status/202354193457343...,1363498642267496459,NaN
15,2023538405251113348,Mon Feb 16 23:35:45 +0000 2026,0,Daripada sibuk salty sama lpdp mending melek n...,2023541843162693835,NaN,wahanakoa,in,NaN,0,1,0,https://x.com/undefined/status/202354184316269...,1705036648537640960,NaN
16,2023541643572658347,Mon Feb 16 23:35:37 +0000 2026,0,sakit hati bgt sih lu ga dpt lpdp anjg. toh jg...,2023541810564657659,NaN,c00stereo,in,NaN,0,1,0,https://x.com/undefined/status/202354181056465...,1109962022471401472,NaN
17,2023340345388658712,Mon Feb 16 23:34:46 +0000 2026,2,@julidAkalsehat @O5Bravo Nah berarti lu belum ...,2023541596902617495,NaN,julidAkalsehat,in,NaN,0,3,0,https://x.com/undefined/status/202354159690261...,1887738122198536192,NaN
18,2023340345388658712,Mon Feb 16 23:33:24 +0000 2026,0,@_blublur @O5Bravo At least empati yg dibutuhk...,2023541251514266089,NaN,_blublur,in,NaN,0,0,0,https://x.com/undefined/status/202354125151426...,995608107370692608,NaN

In [26]:
df.to_csv('/content/drive/MyDrive/Int Conference/Hasil Crawling//lpdp_februari_2026_35.csv', index=False)