In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

In [ ]:
# @title
KH2013 = pd.read_csv('/content/drive/MyDrive/TA DATA PREPROCESSING/Crawling Ulang/Merged/Merged 2013.csv')
KH2014 = pd.read_csv('/content/drive/MyDrive/TA DATA PREPROCESSING/Crawling Ulang/Merged/Merged 2014.csv')
KH2015 = pd.read_csv('/content/drive/MyDrive/TA DATA PREPROCESSING/Crawling Ulang/Merged/Merged 2015.csv')

# JB2013 = pd.read_csv('/content/drive/MyDrive/TA DATA PREPROCESSING/JB2013.csv')
# JB2014 = pd.read_csv('/content/drive/MyDrive/TA DATA PREPROCESSING/JB2014.csv')
# JB2015 = pd.read_csv('/content/drive/MyDrive/TA DATA PREPROCESSING/JB2015.csv')

In [ ]:
# @title
KH2013

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,2.861030e+17,Tue Jan 01 13:33:55 +0000 2013,0,Banjir gunung meletus kebakaran hutan=))) @sal...,2.861030e+17,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/286102959098572800,336648430,NaN
1,2.860860e+17,Tue Jan 01 12:27:48 +0000 2013,0,Lo gatau gue ? Gue itu CHO KYUHYUN yang kece b...,2.860860e+17,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/286086321192194048,770994858,NaN
2,2.860840e+17,Tue Jan 01 12:17:57 +0000 2013,0,Hatiku yg trbakar pik. BwakakakRT @papiipii: p...,2.860840e+17,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/286083839107936257,107340141,NaN
3,2.860700e+17,Tue Jan 01 11:23:47 +0000 2013,0,Disekolah aja masak ampe kebakaran gt ndanio h...,2.860700e+17,NaN,NaN,in,NaN,0,1,0,https://x.com/undefined/status/286070211248013312,978307728,NaN
4,2.859560e+17,Tue Jan 01 03:50:29 +0000 2013,0,:| @andiyudha05: Karna kebakaran kalee @cintya...,2.859560e+17,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/285956133846388736,311805426,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16674,3.963110e+17,Fri Nov 01 16:28:02 +0000 2013,0,@Rahayuayyu huahahaha jgn lupa gunung meletus ...,3.963130e+17,NaN,Rahayuayyu,in,NaN,0,1,0,https://x.com/undefined/status/396312689544134656,41114933,NaN
16675,3.962860e+17,Fri Nov 01 15:14:01 +0000 2013,0,@FakhriJati yaa di data sekitar 18 orang om. E...,3.962940e+17,NaN,FakhriJati,in,NaN,0,1,0,https://x.com/undefined/status/396294060312252416,194864778,NaN
16676,3.961720e+17,Fri Nov 01 07:07:29 +0000 2013,0,KEBAKARAN HUTAN: 22 Personel Disiagakan di Seg...,3.961720e+17,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/396171622257668097,478411653,NaN
16677,3.961680e+17,Fri Nov 01 06:51:22 +0000 2013,0,Ikut ngerokok @DiloIraIndasari: mau mati sudah...,3.961680e+17,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/396167563031216128,160995440,NaN
16678,3.961650e+17,Fri Nov 01 06:39:32 +0000 2013,0,Suruh mereka telan asap nya hahaa @DiloIraInd...,3.961650e+17,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/396164586467905539,549140384,NaN

In [ ]:
# @title
KH2013.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16679 entries, 0 to 16678
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   conversation_id_str      16679 non-null  float64
 1   created_at               16679 non-null  object
 2   favorite_count           16679 non-null  int64
 3   full_text                16679 non-null  object
 4   id_str                   16679 non-null  float64
 5   image_url                283 non-null    object
 6   in_reply_to_screen_name  1292 non-null   object
 7   lang                     16679 non-null  object
 8   location                 0 non-null      float64
 9   quote_count              16679 non-null  int64
 10  reply_count              16679 non-null  int64
 11  retweet_count            16679 non-null  int64
 12  tweet_url                16679 non-null  object
 13  user_id_str              16679 non-null  int64
 14  username                 0 non-null      float64
dtypes: float64(4), int64(5), object(6)
memory usage: 1.9+ MB

In [ ]:
# @title
choosed_column = ['created_at','full_text']

In [ ]:
# @title
KH2013_clean = KH2013.copy()

In [ ]:
# @title
KH2013_clean

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,2.861030e+17,Tue Jan 01 13:33:55 +0000 2013,0,Banjir gunung meletus kebakaran hutan=))) @sal...,2.861030e+17,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/286102959098572800,336648430,NaN
1,2.860860e+17,Tue Jan 01 12:27:48 +0000 2013,0,Lo gatau gue ? Gue itu CHO KYUHYUN yang kece b...,2.860860e+17,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/286086321192194048,770994858,NaN
2,2.860840e+17,Tue Jan 01 12:17:57 +0000 2013,0,Hatiku yg trbakar pik. BwakakakRT @papiipii: p...,2.860840e+17,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/286083839107936257,107340141,NaN
3,2.860700e+17,Tue Jan 01 11:23:47 +0000 2013,0,Disekolah aja masak ampe kebakaran gt ndanio h...,2.860700e+17,NaN,NaN,in,NaN,0,1,0,https://x.com/undefined/status/286070211248013312,978307728,NaN
4,2.859560e+17,Tue Jan 01 03:50:29 +0000 2013,0,:| @andiyudha05: Karna kebakaran kalee @cintya...,2.859560e+17,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/285956133846388736,311805426,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16674,3.963110e+17,Fri Nov 01 16:28:02 +0000 2013,0,@Rahayuayyu huahahaha jgn lupa gunung meletus ...,3.963130e+17,NaN,Rahayuayyu,in,NaN,0,1,0,https://x.com/undefined/status/396312689544134656,41114933,NaN
16675,3.962860e+17,Fri Nov 01 15:14:01 +0000 2013,0,@FakhriJati yaa di data sekitar 18 orang om. E...,3.962940e+17,NaN,FakhriJati,in,NaN,0,1,0,https://x.com/undefined/status/396294060312252416,194864778,NaN
16676,3.961720e+17,Fri Nov 01 07:07:29 +0000 2013,0,KEBAKARAN HUTAN: 22 Personel Disiagakan di Seg...,3.961720e+17,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/396171622257668097,478411653,NaN
16677,3.961680e+17,Fri Nov 01 06:51:22 +0000 2013,0,Ikut ngerokok @DiloIraIndasari: mau mati sudah...,3.961680e+17,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/396167563031216128,160995440,NaN
16678,3.961650e+17,Fri Nov 01 06:39:32 +0000 2013,0,Suruh mereka telan asap nya hahaa @DiloIraInd...,3.961650e+17,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/396164586467905539,549140384,NaN

In [ ]:
# @title
KH2013_clean.rename(columns={"created_at": "timestamp"}, inplace=True)
KH2013_clean.rename(columns={"full_text": "raw_text"}, inplace=True)

In [ ]:
# @title
KH2014

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,reply_count,retweet_count,tweet_url,user_id_str,username
0,4.268160e+17,Fri Jan 24 20:35:30 +0000 2014,0,Lo gatau gue ? Gue itu CHO KYUHYUN yang kece b...,4.268160e+17,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/426815544923131904,770994858,NaN
1,4.267820e+17,Fri Jan 24 18:23:50 +0000 2014,0,Diteliti Pola Pikir Pelaku Pembakaran Hutan di...,4.267820e+17,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/426782410454228992,234305908,NaN
2,4.267820e+17,Fri Jan 24 18:23:48 +0000 2014,0,#Crawler Diteliti Pola Pikir Pelaku Pembakaran...,4.267820e+17,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/426782401528725504,1017444950,NaN
3,4.267820e+17,Fri Jan 24 18:23:26 +0000 2014,0,Diteliti Pola Pikir Pelaku Pembakaran Hutan di...,4.267820e+17,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/426782309342134272,2294578194,NaN
4,4.267820e+17,Fri Jan 24 18:23:15 +0000 2014,0,Diteliti Pola Pikir Pelaku Pembakaran Hutan di...,4.267820e+17,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/426782263733280768,2271505591,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40593,5.372950e+17,Tue Nov 25 17:23:03 +0000 2014,0,Moratorium Hutan Dinilai Tak Jamin Efektif Tan...,5.372950e+17,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/537295413959618560,2187882060,NaN
40594,5.372950e+17,Tue Nov 25 17:23:01 +0000 2014,0,Moratorium Hutan Dinilai Tak Jamin Efektif Tan...,5.372950e+17,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/537295404430159872,240182586,NaN
40595,5.372950e+17,Tue Nov 25 17:23:00 +0000 2014,0,Moratorium Hutan Dinilai Tak Jamin Efektif Tan...,5.372950e+17,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/537295401406042112,909920736,NaN
40596,5.372950e+17,Tue Nov 25 17:22:41 +0000 2014,0,@info: Moratorium Hutan Dinilai Tak Jamin Efek...,5.372950e+17,NaN,INFO,in,NaN,0,0,0,https://x.com/undefined/status/537295319419994113,15503908,NaN
40597,5.372950e+17,Tue Nov 25 17:22:40 +0000 2014,0,Moratorium Hutan Dinilai Tak Jamin Efektif Tan...,5.372950e+17,NaN,NaN,in,NaN,0,0,0,https://x.com/undefined/status/537295317159272448,2276871246,NaN

In [ ]:
# @title
KH2014_clean = KH2014.copy()

In [ ]:
# @title
KH2015_clean = KH2015.copy()

In [ ]:
# @title
JB2013

,Datetime,Tweet Url,Text,Username,User Created,Verified,Followers Count,Retweet Count,Like Count,Reply Count,Hashtags
0,2013-12-30 19:55:38+00:00,https://twitter.com/amanfirdaus/status/4177458...,Jerebu? http://t.co/7Om1KfN3zu,amanfirdaus,2008-07-24 06:47:46+00:00,False,12537,1,0,1,NaN
1,2013-12-30 18:04:44+00:00,https://twitter.com/Forgotlah/status/417717907...,@sheikhf184 hahaha cuak wei kalau jerebu lagi,Forgotlah,2011-08-08 08:00:31+00:00,False,521,0,0,0,NaN
2,2013-12-30 17:28:19+00:00,https://twitter.com/mariatulshzleen/status/417...,"""@AzrilVienna: Tebalnya bedak awak tu kalau s...",mariatulshzleen,2012-08-06 17:39:30+00:00,False,583,0,0,0,NaN
3,2013-12-30 16:27:09+00:00,https://twitter.com/amshfqa17/status/417693348...,@fazleenans jerebu mu,amshfqa17,2011-06-07 06:38:35+00:00,False,119,0,0,0,NaN
4,2013-12-30 16:11:52+00:00,https://twitter.com/sarawakupdate/status/41768...,Ooops sorry. Jerebu dari supplier baharu. http...,sarawakupdate,2009-05-25 01:04:26+00:00,False,18619,1,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
7496,2013-08-28 05:47:00+00:00,https://twitter.com/AiemenRazieq/status/372596...,Sebab tak teruk RT @ahmdpaan: kenapa jerebu ka...,AiemenRazieq,2011-04-11 12:07:40+00:00,False,554,1,0,0,NaN
7497,2013-08-28 05:46:24+00:00,https://twitter.com/AswariBasri/status/3725960...,@haniZulkifflee wehh kat tempat aq puN jerebu ...,AswariBasri,2012-09-15 07:42:27+00:00,False,578,0,0,2,NaN
7498,2013-08-28 05:45:46+00:00,https://twitter.com/ainashahiera/status/372595...,Kuatnya angin di seri iskandar. Jerebu pun mun...,ainashahiera,2009-11-02 03:27:46+00:00,False,533,0,0,0,NaN
7499,2013-08-28 05:45:25+00:00,https://twitter.com/FaraMohdSehat/status/37259...,Kedah jerebu erkkk .,FaraMohdSehat,2012-02-11 03:28:05+00:00,False,232,1,0,1,NaN
7500,2013-08-28 05:45:22+00:00,https://twitter.com/ajakamal93/status/37259574...,Awat sekarang nih nampak kulim berasap? Jerebu...,ajakamal93,2012-05-16 17:01:48+00:00,False,158,0,0,0,NaN

In [ ]:
# @title
JB2013_clean=JB2013.loc[:, choosed_column]

In [ ]:
# @title
JB2013_clean

,Datetime,Text
0,2013-12-30 19:55:38+00:00,Jerebu? http://t.co/7Om1KfN3zu
1,2013-12-30 18:04:44+00:00,@sheikhf184 hahaha cuak wei kalau jerebu lagi
2,2013-12-30 17:28:19+00:00,"""@AzrilVienna: Tebalnya bedak awak tu kalau s..."
3,2013-12-30 16:27:09+00:00,@fazleenans jerebu mu
4,2013-12-30 16:11:52+00:00,Ooops sorry. Jerebu dari supplier baharu. http...
...,...,...
7496,2013-08-28 05:47:00+00:00,Sebab tak teruk RT @ahmdpaan: kenapa jerebu ka...
7497,2013-08-28 05:46:24+00:00,@haniZulkifflee wehh kat tempat aq puN jerebu ...
7498,2013-08-28 05:45:46+00:00,Kuatnya angin di seri iskandar. Jerebu pun mun...
7499,2013-08-28 05:45:25+00:00,Kedah jerebu erkkk .
7500,2013-08-28 05:45:22+00:00,Awat sekarang nih nampak kulim berasap? Jerebu...

In [ ]:
# @title
JB2014_clean=JB2014.loc[:, choosed_column]

In [ ]:
# @title
JB2015_clean=JB2015.loc[:, choosed_column]

In [ ]:
# @title
KH2014_clean.rename(columns={"created_at": "timestamp"}, inplace=True)
KH2014_clean.rename(columns={"full_text": "raw_text"}, inplace=True)
KH2015_clean.rename(columns={"created_at": "timestamp"}, inplace=True)
KH2015_clean.rename(columns={"full_text": "raw_text"}, inplace=True)

# JB2013_clean.rename(columns={"Datetime": "timestamp"}, inplace=True)
# JB2013_clean.rename(columns={"Text": "raw_text"}, inplace=True)
# JB2014_clean.rename(columns={"Datetime": "timestamp"}, inplace=True)
# JB2014_clean.rename(columns={"Text": "raw_text"}, inplace=True)
# JB2015_clean.rename(columns={"Datetime": "timestamp"}, inplace=True)
# JB2015_clean.rename(columns={"Text": "raw_text"}, inplace=True)

In [ ]:
# @title
KH2015_clean.rename(columns={"created_at": "timestamp"}, inplace=True)
KH2015_clean.rename(columns={"full_text": "raw_text"}, inplace=True)

In [ ]:
# @title
path ='/content/drive/MyDrive/TA DATA PREPROCESSING/Crawling Ulang/Data Clean'

In [ ]:
# @title
KH2013_clean.to_csv(f'{path}KH2013_cleaned.csv', index=False)
KH2014_clean.to_csv(f'{path}KH2014_cleaned.csv', index=False)
KH2015_clean.to_csv(f'{path}KH2015_cleaned.csv', index=False)

# JB2013_clean.to_csv(f'{path}JB2013_clean.csv', index=False)
# JB2014_clean.to_csv(f'{path}JB2014_clean.csv', index=False)
# JB2015_clean.to_csv(f'{path}JB2015_clean.csv', index=False)

### **DATA PREPROCESSING**

In [ ]:
# @title
!pip install nltk
!pip install Sastrawi

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.1)
Collecting Sastrawi
  Downloading Sastrawi-1.0.1-py2.py3-none-any.whl.metadata (909 bytes)
Downloading Sastrawi-1.0.1-py2.py3-none-any.whl (209 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 209.7/209.7 kB 14.1 MB/s eta 0:00:00
Installing collected packages: Sastrawi
Successfully installed Sastrawi-1.0.1

In [ ]:
# @title
import nltk
from nltk.corpus import stopwords
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
import re

In [ ]:
# @title
try:
    stopwords.words('indonesian')
except LookupError:
    nltk.download('stopwords')

# Stopword bahasa Indonesia
stop_id = set(stopwords.words('indonesian'))

# Stopword bahasa Malaysia
stop_my = {
    "yang","dengan","untuk","pada","ada","akan","saya","awak","kami","kita",
    "dia","mereka","ini","itu","jadi","kerana","oleh","dari","dan","atau",
    "dalam","sebagai","bagi","juga","lagi","semua","tak","x"
}

# Jangan hapus kata negasi penting
negations_id = {"tidak", "bukan", "jangan", "ga", "gak", "nggak", "tak"}
negations_my = {"tak", "x", "tidak", "jangan", "bukan"}
stop_my = stop_my - negations_my
stop_id = stop_id - negations_id

# Stemmer Bahasa Indonesia
factory = StemmerFactory()
stemmer = factory.create_stemmer()

# Kamus slang sederhana
normalization_dict_id = {
    "gk": "tidak",
    "ga": "tidak",
    "gak": "tidak",
    "nggak": "tidak",
    "tdk": "tidak",
    "yg": "yang",
    "dgn": "dengan",
    "dr": "dari",
    "tp": "tapi",
    "klo": "kalau",
    "kl": "kalau",
    "aja": "saja"
}
normalization_dict_my = {
    "sy": "saya",
    "u": "awak",
    "awakmu": "awak",
    "mlm": "malam",
    "dpt": "dapat",
    "takde": "tidak ada",
    "xde": "tidak ada",
    "x":"tidak"
}

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

LOWER CASE

In [ ]:
# @title
KH2013_clean["lower_text"] = KH2013_clean["raw_text"].str.lower()
KH2014_clean["lower_text"] = KH2014_clean["raw_text"].str.lower()
KH2015_clean["lower_text"] = KH2015_clean["raw_text"].str.lower()

# JB2013_clean["lower_text"] = JB2013_clean["raw_text"].str.lower()
# JB2014_clean["lower_text"] = JB2014_clean["raw_text"].str.lower()
# JB2015_clean["lower_text"] = JB2015_clean["raw_text"].str.lower()

In [ ]:
# @title
KH2015_clean["lower_text"] = KH2015_clean["raw_text"].str.lower()

NO URL

In [ ]:
# @title
KH2013_clean['lower_text'] = KH2013_clean['lower_text'].astype(str)
KH2014_clean['lower_text'] = KH2014_clean['lower_text'].astype(str)
KH2015_clean['lower_text'] = KH2015_clean['lower_text'].astype(str)

# JB2013_clean['lower_text'] = JB2013_clean['lower_text'].astype(str)
# JB2014_clean['lower_text'] = JB2014_clean['lower_text'].astype(str)
# JB2015_clean['lower_text'] = JB2015_clean['lower_text'].astype(str)

In [ ]:
# @title
KH2015_clean['lower_text'] = KH2015_clean['lower_text'].astype(str)

In [ ]:
# @title
KH2013_clean["no_url"] = KH2013_clean["lower_text"].apply(
    lambda x: re.sub(r"http\S+|www\S+|https\S+", "", x)
)
KH2014_clean["no_url"] = KH2014_clean["lower_text"].apply(
    lambda x: re.sub(r"http\S+|www\S+|https\S+", "", x)
)
KH2015_clean["no_url"] = KH2015_clean["lower_text"].apply(
    lambda x: re.sub(r"http\S+|www\S+|https\S+", "", x)
)

# JB2013_clean["no_url"] = JB2013_clean["lower_text"].apply(
#     lambda x: re.sub(r"http\S+|www\S+|https\S+", "", x)
# )
# JB2014_clean["no_url"] = JB2014_clean["lower_text"].apply(
#     lambda x: re.sub(r"http\S+|www\S+|https\S+", "", x)
# )
# JB2015_clean["no_url"] = JB2015_clean["lower_text"].apply(
#     lambda x: re.sub(r"http\S+|www\S+|https\S+", "", x)
# )

In [ ]:
# @title
KH2015_clean["no_url"] = KH2015_clean["lower_text"].apply(
    lambda x: re.sub(r"http\S+|www\S+|https\S+", "", x)
)

Hapus Mention & Hashtag + Segmentasi Hashtag

In [ ]:
# @title
def clean_mentions_hashtags(text):
    # Hapus mention
    text = re.sub(r"@\w+", "", text)
    # Ganti hashtag jadi kata tanpa "#"
    text = re.sub(r"#(\w+)", r"\1", text)
    return text

In [ ]:
# @title
KH2013_clean["no_mention_hashtag"] = KH2013_clean["no_url"].apply(clean_mentions_hashtags)
KH2014_clean["no_mention_hashtag"] = KH2014_clean["no_url"].apply(clean_mentions_hashtags)
KH2015_clean["no_mention_hashtag"] = KH2015_clean["no_url"].apply(clean_mentions_hashtags)

# JB2013_clean["no_mention_hashtag"] = JB2013_clean["no_url"].apply(clean_mentions_hashtags)
# JB2014_clean["no_mention_hashtag"] = JB2014_clean["no_url"].apply(clean_mentions_hashtags)
# JB2015_clean["no_mention_hashtag"] = JB2015_clean["no_url"].apply(clean_mentions_hashtags)

In [ ]:
# @title
KH2015_clean["no_mention_hashtag"] = KH2015_clean["no_url"].apply(clean_mentions_hashtags)

Normalisasi Slang

In [ ]:
# @title
def normalize_text_id(text):
    return " ".join([normalization_dict_id.get(word, word) for word in text.split()])

In [ ]:
# @title
    KH2013_clean["normalized_text"] = KH2013_clean["no_mention_hashtag"].apply(normalize_text_id)
    KH2014_clean["normalized_text"] = KH2014_clean["no_mention_hashtag"].apply(normalize_text_id)
    KH2015_clean["normalized_text"] = KH2015_clean["no_mention_hashtag"].apply(normalize_text_id)

In [ ]:
# @title
KH2015_clean["normalized_text"] = KH2015_clean["no_mention_hashtag"].apply(normalize_text_id)

In [ ]:
# @title
def normalize_text_my(text):
    return " ".join([normalization_dict_my.get(word, word) for word in text.split()])

In [ ]:
# @title
    JB2013_clean["normalized_text"] = JB2013_clean["no_mention_hashtag"].apply(normalize_text_id)
    JB2014_clean["normalized_text"] = JB2014_clean["no_mention_hashtag"].apply(normalize_text_id)
    JB2015_clean["normalized_text"] = JB2015_clean["no_mention_hashtag"].apply(normalize_text_id)

Normalisasi Pengulangan Karakter

In [ ]:
# @title
def reduce_repeated_chars(text):
    return re.sub(r'(.)\1{2,}', r'\1', text)  # "baguuuusss" -> "bagus"

In [ ]:
# @title
    KH2013_clean["normalized_text"] = KH2013_clean["normalized_text"].apply(reduce_repeated_chars)
    KH2014_clean["normalized_text"] = KH2014_clean["normalized_text"].apply(reduce_repeated_chars)
    KH2015_clean["normalized_text"] = KH2015_clean["normalized_text"].apply(reduce_repeated_chars)

    # JB2013_clean["normalized_text"] = JB2013_clean["normalized_text"].apply(reduce_repeated_chars)
    # JB2014_clean["normalized_text"] = JB2014_clean["normalized_text"].apply(reduce_repeated_chars)
    # JB2015_clean["normalized_text"] = JB2015_clean["normalized_text"].apply(reduce_repeated_chars)

In [ ]:
# @title
KH2015_clean["normalized_text"] = KH2015_clean["normalized_text"].apply(reduce_repeated_chars)

Tokenisasi

In [ ]:
# @title
from nltk.tokenize import TreebankWordTokenizer
tokenizer = TreebankWordTokenizer()


KH2013_clean["tokenized"] = KH2013_clean["normalized_text"].apply(tokenizer.tokenize)
KH2014_clean["tokenized"] = KH2014_clean["normalized_text"].apply(tokenizer.tokenize)
KH2015_clean["tokenized"] = KH2015_clean["normalized_text"].apply(tokenizer.tokenize)

# JB2013_clean["tokenized"] = JB2013_clean["normalized_text"].apply(tokenizer.tokenize)
# JB2014_clean["tokenized"] = JB2014_clean["normalized_text"].apply(tokenizer.tokenize)
# JB2015_clean["tokenized"] = JB2015_clean["normalized_text"].apply(tokenizer.tokenize)

In [ ]:
# @title
from nltk.tokenize import TreebankWordTokenizer
tokenizer = TreebankWordTokenizer()


KH2015_clean["tokenized"] = KH2015_clean["normalized_text"].apply(tokenizer.tokenize)

Stopword Removal

In [ ]:
# @title
#dengan mempertahankan negasi
#id
KH2013_clean["stopword_removed"] = KH2013_clean["tokenized"].apply(
    lambda tokens: [w for w in tokens if w.isalpha() and w not in stop_id]
)
KH2014_clean["stopword_removed"] = KH2014_clean["tokenized"].apply(
    lambda tokens: [w for w in tokens if w.isalpha() and w not in stop_id]
)
KH2015_clean["stopword_removed"] = KH2015_clean["tokenized"].apply(
    lambda tokens: [w for w in tokens if w.isalpha() and w not in stop_id]
)
# #my
# JB2013_clean["stopword_removed"] = JB2013_clean["tokenized"].apply(
#     lambda tokens: [w for w in tokens if w.isalpha() and w not in stop_my]
# )
# JB2014_clean["stopword_removed"] = JB2014_clean["tokenized"].apply(
#     lambda tokens: [w for w in tokens if w.isalpha() and w not in stop_my]
# )
# JB2015_clean["stopword_removed"] = JB2015_clean["tokenized"].apply(
#     lambda tokens: [w for w in tokens if w.isalpha() and w not in stop_my]
# )

In [ ]:
# @title
KH2015_clean["stopword_removed"] = KH2015_clean["tokenized"].apply(
    lambda tokens: [w for w in tokens if w.isalpha() and w not in stop_id]
)

Stemming (Final Text)

In [ ]:
# @title
KH2013_clean["final_text"] = KH2013_clean["stopword_removed"].apply(
    lambda tokens: " ".join([stemmer.stem(w) for w in tokens])
)
KH2014_clean["final_text"] = KH2014_clean["stopword_removed"].apply(
    lambda tokens: " ".join([stemmer.stem(w) for w in tokens])
)
KH2015_clean["final_text"] = KH2015_clean["stopword_removed"].apply(
    lambda tokens: " ".join([stemmer.stem(w) for w in tokens])
)

# JB2013_clean["final_text"] = JB2013_clean["stopword_removed"].apply(
#     lambda tokens: " ".join([stemmer.stem(w) for w in tokens])
# )
# JB2014_clean["final_text"] = JB2014_clean["stopword_removed"].apply(
#     lambda tokens: " ".join([stemmer.stem(w) for w in tokens])
# )
# JB2015_clean["final_text"] = JB2015_clean["stopword_removed"].apply(
#     lambda tokens: " ".join([stemmer.stem(w) for w in tokens])
# )

In [ ]:
# @title
KH2015_clean["final_text"] = KH2015_clean["stopword_removed"].apply(
    lambda tokens: " ".join([stemmer.stem(w) for w in tokens])
)

In [ ]:
# @title
path=('/content/drive/MyDrive/TA DATA PREPROCESSING/Crawling Ulang/Data Clean')

In [ ]:
# @title
KH2013_clean.to_csv(f'{path}KH2013_cleaned_preprocessing.csv', index=False)
KH2014_clean.to_csv(f'{path}KH2014_cleaned_preprocessing.csv', index=False)
KH2015_clean.to_csv(f'{path}KH2015_cleaned_preprocessing.csv', index=False)

# JB2013_clean.to_csv(f'{path}JB2013_clean_preprocessing.csv', index=False)
# JB2014_clean.to_csv(f'{path}JB2014_clean_preprocessing.csv', index=False)
# JB2015_clean.to_csv(f'{path}JB2015_clean_preprocessing.csv', index=False)

In [ ]:
# @title
KH2015_clean.to_csv(f'{path}KH2015_clean_preprocessing.csv', index=False)

### **LABELLING**

TRANSLASI BAHASA INGGRIS

In [ ]:
# @title
LPDP_clean= pd.read_csv('/content/drive/MyDrive/Int Conference/Slang/preprocess baris 1-40k.csv')

In [ ]:
# @title
import ast

LPDP_clean['normalisasi'] = LPDP_clean['normalisasi'].apply(ast.literal_eval)
LPDP_clean['normalisasi_text'] = LPDP_clean['normalisasi'].apply(lambda x: ' '.join(x))

In [ ]:
# @title
# This will show you all the column names that actually exist
print(LPDP_clean.columns.to_list())

['conversation_id_str', 'created_at', 'favorite_count', 'full_text', 'id_str', 'image_url', 'in_reply_to_screen_name', 'lang', 'location', 'quote_count', 'reply_count', 'retweet_count', 'tweet_url', 'user_id_str', 'username', 'filtered', 'cleaned', 'tweet_tokens', 'normalisasi', 'normalisasi_text']

In [ ]:
# @title
from tqdm import tqdm
tqdm.pandas()

LPDP_clean['english_translation'] = LPDP_clean['normalisasi_text'].progress_apply(translate_to_english)

 26%|██▌       | 37897/145870 [7:06:44<20:15:50,  1.48it/s]

KeyboardInterrupt:

In [ ]:
# @title
LPDP_clean.to_csv(
    '/content/drive/MyDrive/Int Conference/Data Clean/LPDP_partial_translation.csv',
    index=False
)

NameError: name 'LPDP_clean' is not defined

In [ ]:
!pip install googletrans==4.0.0-rc1

Collecting googletrans==4.0.0-rc1
  Downloading googletrans-4.0.0rc1.tar.gz (20 kB)
  Preparing metadata (setup.py) ... done
Collecting httpx==0.13.3 (from googletrans==4.0.0-rc1)
  Downloading httpx-0.13.3-py3-none-any.whl.metadata (25 kB)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (2026.2.25)
Collecting hstspreload (from httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading hstspreload-2025.1.1-py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: sniffio in /usr/local/lib/python3.12/dist-packages (from httpx==0.13.3->googletrans==4.0.0-rc1) (1.3.1)
Collecting chardet==3.* (from httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading chardet-3.0.4-py2.py3-none-any.whl.metadata (3.2 kB)
Collecting idna==2.* (from httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading idna-2.10-py2.py3-none-any.whl.metadata (9.1 kB)
Collecting rfc3986<2,>=1.3 (from httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading rfc3986-1.5.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting httpcore==0.9.* (from httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading httpcore-0.9.1-py3-none-any.whl.metadata (4.6 kB)
Collecting h11<0.10,>=0.8 (from httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading h11-0.9.0-py2.py3-none-any.whl.metadata (8.1 kB)
Collecting h2==3.* (from httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading h2-3.2.0-py2.py3-none-any.whl.metadata (32 kB)
Collecting hyperframe<6,>=5.2.0 (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading hyperframe-5.2.0-py2.py3-none-any.whl.metadata (7.2 kB)
Collecting hpack<4,>=3.0 (from h2==3.*->httpcore==0.9.*->httpx==0.13.3->googletrans==4.0.0-rc1)
  Downloading hpack-3.0.0-py2.py3-none-any.whl.metadata (7.0 kB)
Downloading httpx-0.13.3-py3-none-any.whl (55 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.1/55.1 kB 4.8 MB/s eta 0:00:00
Downloading chardet-3.0.4-py2.py3-none-any.whl (133 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.4/133.4 kB 6.4 MB/s eta 0:00:00
Downloading httpcore-0.9.1-py3-none-any.whl (42 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 3.2 MB/s eta 0:00:00
Downloading idna-2.10-py2.py3-none-any.whl (58 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.8/58.8 kB 5.1 MB/s eta 0:00:00
Downloading h2-3.2.0-py2.py3-none-any.whl (65 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.0/65.0 kB 5.4 MB/s eta 0:00:00
Downloading rfc3986-1.5.0-py2.py3-none-any.whl (31 kB)
Downloading hstspreload-2025.1.1-py3-none-any.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 31.6 MB/s eta 0:00:00
Downloading h11-0.9.0-py2.py3-none-any.whl (53 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.6/53.6 kB 4.3 MB/s eta 0:00:00
Downloading hpack-3.0.0-py2.py3-none-any.whl (38 kB)
Downloading hyperframe-5.2.0-py2.py3-none-any.whl (12 kB)
Building wheels for collected packages: googletrans
  Building wheel for googletrans (setup.py) ... done
  Created wheel for googletrans: filename=googletrans-4.0.0rc1-py3-none-any.whl size=17396 sha256=efa589b9bacef2ac1c6d6b67ba0d8956b4223176c3389b18d5c84f5df4594666
  Stored in directory: /root/.cache/pip/wheels/95/0f/04/b17a72024b56a60e499ce1a6313d283ed5ba332407155bee03
Successfully built googletrans
Installing collected packages: rfc3986, hyperframe, hpack, h11, chardet, idna, hstspreload, h2, httpcore, httpx, googletrans
  Attempting uninstall: hyperframe
    Found existing installation: hyperframe 6.1.0
    Uninstalling hyperframe-6.1.0:
      Successfully uninstalled hyperframe-6.1.0
  Attempting uninstall: hpack
    Found existing installation: hpack 4.1.0
    Uninstalling hpack-4.1.0:
      Successfully uninstalled hpack-4.1.0
  Attempting uninstall: h11
    Found existing installation: h11 0.16.0
    Uninstalling h11-0.16.0:
      Successfully uninstalled h11-0.16.0
  Attempting uninstall: chardet
    Found existing installation: chardet 5.2.0
    Uninstalling chardet-5.2.0:
      Successfully uninstalled chardet-5.2.0
  Attempting uninstall: idna
    Found existing installation: idna 3.11
    Uninstalling idna-3.11:
      Successfully uninstalled idna-3.11
  Attempting uninstall: h2
    Found existing installation: h2 4.3.0
    Uninstalling h2-4.3.0:
      Successfully uninstalled h2-4.3.0
  Attempting uninstall: httpcore
    Found existing installation: httpcore 1.0.9
    Uninstalling httpcore-1.0.9:
      Successfully uninstalled httpcore-1.0.9
  Attempting uninstall: httpx
    Found existing installation: httpx 0.28.1
    Uninstalling httpx-0.28.1:
      Successfully uninstalled httpx-0.28.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
openai 2.24.0 requires httpx<1,>=0.23.0, but you have httpx 0.13.3 which is incompatible.
google-genai 1.65.0 requires httpx<1.0.0,>=0.28.1, but you have httpx 0.13.3 which is incompatible.
langgraph-sdk 0.3.9 requires httpx>=0.25.2, but you have httpx 0.13.3 which is incompatible.
firebase-admin 6.9.0 requires httpx[http2]==0.28.1, but you have httpx 0.13.3 which is incompatible.
gradio 5.50.0 requires httpx<1.0,>=0.24.1, but you have httpx 0.13.3 which is incompatible.
mcp 1.26.0 requires httpx>=0.27.1, but you have httpx 0.13.3 which is incompatible.
huggingface-hub 1.5.0 requires httpx<1,>=0.23.0, but you have httpx 0.13.3 which is incompatible.
langsmith 0.7.7 requires httpx<1,>=0.23.0, but you have httpx 0.13.3 which is incompatible.
gradio-client 1.14.0 requires httpx>=0.24.1, but you have httpx 0.13.3 which is incompatible.
google-adk 1.26.0 requires httpx<1.0.0,>=0.27.0, but you have httpx 0.13.3 which is incompatible.
Successfully installed chardet-3.0.4 googletrans-4.0.0rc1 h11-0.9.0 h2-3.2.0 hpack-3.0.0 hstspreload-2025.1.1 httpcore-0.9.1 httpx-0.13.3 hyperframe-5.2.0 idna-2.10 rfc3986-1.5.0

In [ ]:
#id
from googletrans import Translator
translator = Translator()
def translate_to_english(text):
    if isinstance(text, str) and text.strip():
        try:
            return translator.translate(text, dest='en').text
        except Exception:
            return "" # Kembalikan string kosong jika gagal

    return ""

In [ ]:
LPDP_clean = pd.read_csv(
    '/content/drive/MyDrive/Int Conference/Data Clean/LPDP_partial_translation.csv'
)

In [ ]:
# LPDP_clean['english_translation'] = ""

In [ ]:
mask = LPDP_clean['english_translation'].isna() | (LPDP_clean['english_translation'] == "")

subset = LPDP_clean.loc[mask]

In [ ]:
from tqdm import tqdm
tqdm.pandas()

batch_size = 1000

for start in range(0, len(subset), batch_size):
    end = start + batch_size

    indices = subset.index[start:end]

    LPDP_clean.loc[indices, 'english_translation'] = \
        LPDP_clean.loc[indices, 'normalisasi_text'].progress_apply(translate_to_english)

    # AUTO SAVE tiap batch
    LPDP_clean.to_csv(
        '/content/drive/MyDrive/Int Conference/Data Clean/LPDP_partial_translation.csv',
        index=False
    )

    print(f"Saved batch {start} to {end}")

100%|██████████| 1000/1000 [02:54<00:00,  5.72it/s]

Saved batch 0 to 1000

100%|██████████| 1000/1000 [13:15<00:00,  1.26it/s]

Saved batch 1000 to 2000

100%|██████████| 1000/1000 [16:32<00:00,  1.01it/s]

Saved batch 2000 to 3000

100%|██████████| 1000/1000 [16:33<00:00,  1.01it/s]

Saved batch 3000 to 4000

100%|██████████| 1000/1000 [15:52<00:00,  1.05it/s]

Saved batch 4000 to 5000

100%|██████████| 1000/1000 [16:06<00:00,  1.03it/s]

Saved batch 5000 to 6000

100%|██████████| 1000/1000 [15:29<00:00,  1.08it/s]

Saved batch 6000 to 7000

100%|██████████| 647/647 [10:07<00:00,  1.07it/s]

Saved batch 7000 to 8000

In [ ]:
path=('/content/drive/MyDrive/Int Conference/Data Clean/')

In [ ]:
LPDP_clean.to_csv(f'{path}LPDP_cleaned_preprocessing.csv', index=False)

labelling-text blob

In [ ]:
!pip install textblob

Requirement already satisfied: textblob in /usr/local/lib/python3.12/dist-packages (0.19.0)
Requirement already satisfied: nltk>=3.9 in /usr/local/lib/python3.12/dist-packages (from textblob) (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (4.67.3)

In [ ]:
from textblob import TextBlob

def label_textblob(text):
    if isinstance(text, str):
        polarity = TextBlob(text).sentiment.polarity
        if polarity > 0:
            return "Positif"
        elif polarity < 0:
            return "Negatif"
        else:
            return "Netral"
    return "Netral"

In [ ]:
LPDP_clean['label_textblob'] = LPDP_clean['english_translation'].apply(label_textblob)

labelling-vader

In [ ]:
!pip install vaderSentiment

Collecting vaderSentiment
  Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl.metadata (572 bytes)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from vaderSentiment) (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->vaderSentiment) (2026.2.25)
Downloading vaderSentiment-3.3.2-py2.py3-none-any.whl (125 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 126.0/126.0 kB 4.1 MB/s eta 0:00:00
Installing collected packages: vaderSentiment
Successfully installed vaderSentiment-3.3.2

In [ ]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()

def label_vader(text):
    if isinstance(text, str):
        score = analyzer.polarity_scores(text)
        if score['compound'] >= 0.05:
            return "Positif"
        elif score['compound'] <= -0.05:
            return "Negatif"
        else:
            return "Netral"
    return "Netral"

In [ ]:
LPDP_clean['label_vader'] = LPDP_clean['english_translation'].apply(label_vader)

labelling-senti(afinn)

In [ ]:
!pip install afinn

Collecting afinn
  Downloading afinn-0.1.tar.gz (52 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.6/52.6 kB 2.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: afinn
  Building wheel for afinn (setup.py) ... done
  Created wheel for afinn: filename=afinn-0.1-py3-none-any.whl size=53431 sha256=927c111cf2413463b06fe70e9f39d89e96c33cfcfc93898fe123aa79fd03f868
  Stored in directory: /root/.cache/pip/wheels/f9/72/27/74994e77200dae3d6aea2b546264500cee21f738c51241320b
Successfully built afinn
Installing collected packages: afinn
Successfully installed afinn-0.1

In [ ]:
from afinn import Afinn

afinn = Afinn()

def label_senti_afinn(text):
    if isinstance(text, str):
        score = afinn.score(text)
        if score > 0:
            return "Positif"
        elif score < 0:
            return "Negatif"
        else:
            return "Netral"
    return "Netral"

In [ ]:
LPDP_clean['label_senti_afinn'] = LPDP_clean['english_translation'].apply(label_senti_afinn)

In [ ]:
LPDP_clean

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,...,username,filtered,cleaned,tweet_tokens,normalisasi,normalisasi_text,english_translation,label_textblob,label_vader,label_senti_afinn
0,1.340000e+18,Fri Jan 01 01:33:05 +0000 2021,1,Lowongan Kerja BUMN LPDP Kemenkeu Terbaru Dese...,1.340000e+18,NaN,NaN,in,NaN,0,...,NaN,lowongan kerja bumn lpdp kemenkeu terbaru dese...,lowong kerja bumn lpdp kemenkeu baru desember,"['lowong', 'kerja', 'bumn', 'lpdp', 'kemenkeu'...","['lowong', 'kerja', 'bumn', 'lpdp', 'kemenkeu'...",lowong kerja bumn lpdp kemenkeu baru desember,New BUMN LPDP Kemenkeu job vacancies December,Positif,Netral,Netral
1,1.340000e+18,Fri Jan 01 03:01:50 +0000 2021,8,@jawafess 2020 ku wes cukup absurd tulong. 202...,1.340000e+18,NaN,jawafess,in,NaN,0,...,NaN,ku wes cukup absurd tulong ku pengen luwih ter...,ku wes cukup absurd tulong ku ken luwih tata m...,"['ku', 'wes', 'cukup', 'absurd', 'tulong', 'ku...","['ku', 'wes', 'cukup', 'absurd', 'tulong', 'ku...",ku wes cukup absurd tulong ku ken luwih tata m...,"I'm quite absurd, I can help you to win the so...",Positif,Positif,Positif
2,1.190000e+18,Fri Jan 01 03:16:45 +0000 2021,0,@indo35meme Lpdp apa ya? ï¸,1.340000e+18,NaN,indo35meme,in,NaN,0,...,NaN,lpdp apa ya,lpdp apa,"['lpdp', 'apa']","['lpdp', 'apa']",lpdp apa,what lpdp,Netral,Netral,Netral
3,1.340000e+18,Fri Jan 01 03:52:46 +0000 2021,1,Lowongan Rekrutmen LPDP Kemenkeu....Info lengk...,1.340000e+18,https://pbs.twimg.com/media/EqnhoYgVEAM5E5i.jpg,NaN,in,NaN,0,...,NaN,lowongan rekrutmen lpdp kemenkeu info lengkap,lowong rekrutmen lpdp kemenkeu info lengkap,"['lowong', 'rekrutmen', 'lpdp', 'kemenkeu', 'i...","['lowong', 'rekrutmen', 'lpdp', 'kemenkeu', 'i...",lowong rekrutmen lpdp kemenkeu info lengkap,vacancies for lpdp recruitment for the Ministr...,Positif,Netral,Netral
4,1.340000e+18,Fri Jan 01 06:33:18 +0000 2021,0,@RamaWijanarko Hai LPDPrens terima kasih atas ...,1.340000e+18,NaN,NaN,in,NaN,0,...,NaN,hai lpdprens terima kasih atas sharingnya ya s...,hai lpdprens terima kasih atas sharingnya moga...,"['hai', 'lpdprens', 'terima', 'kasih', 'atas',...","['hai', 'lpdprens', 'terima', 'kasih', 'atas',...",hai lpdprens terima kasih atas sharingnya moga...,"hi lpdprens, thank you for sharing, hopefully ...",Positif,Positif,Positif
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145865,2.027890e+18,Sat Feb 28 23:38:09 +0000 2026,0,Lpdp harvard law alumni cuman buat jd tour gui...,2.027890e+18,NaN,NaN,in,NaN,0,...,NaN,lpdp harvard law alumni cuman buat jd tour gui...,lpdp harvard law alumni cuman jd tour guide ba...,"['lpdp', 'harvard', 'law', 'alumni', 'cuman', ...","['lpdp', 'harvard', 'law', 'alumni', 'hanya', ...",lpdp harvard law alumni hanya jd tour guide ba...,lpdp harvard law alumni only act as tour guide...,Positif,Positif,Positif
145866,2.027680e+18,Sat Feb 28 23:42:18 +0000 2026,0,@bagus_muljadi Argumen bagus menggeser diskusi...,2.027890e+18,NaN,bagus_muljadi,in,NaN,0,...,NaN,muljadi argumen bagus menggeser diskusi dari m...,muljadi argumen bagus geser diskusi moral teri...,"['muljadi', 'argumen', 'bagus', 'geser', 'disk...","['muljadi', 'argumen', 'bagus', 'geser', 'disk...",muljadi argumen bagus geser diskusi moral teri...,muljadi good argument slide moral discussion a...,Positif,Positif,Positif
145867,2.027680e+18,Sat Feb 28 23:44:18 +0000 2026,0,@bagus_muljadi 4. kolaborasi LPDP Kemendikbud ...,2.027890e+18,NaN,bagus_muljadi,in,NaN,0,...,NaN,muljadi kolaborasi lpdp kemendikbud untuk pipe...,muljadi kolaborasi lpdp kemendikbud untuk pipe...,"['muljadi', 'kolaborasi', 'lpdp', 'kemendikbud...","['muljadi', 'kolaborasi', 'lpdp', 'kemendikbud...",muljadi kolaborasi lpdp kemendikbud untuk pipe...,muljadi collaboration of the Ministry of Educa...,Netral,Positif,Positif
145868,2.027010e+18,Sat Feb 28 23:45:59 +0000 2026,0,@ejaeyun Rill no trust issue ga lpdp ga php Mi...,2.027890e+18,https://pbs.twimg.com/tweet_video_thumb/HCSF_z...,ejaeyun,en,NaN,0,...,NaN,rill no trust issue ga lpdp ga php min,rill no trust issue ga lpdp ga php min,"['rill', 'no', 'trust', 'issue', 'ga', 'lpdp',...","['rill', 'no', 'trust', 'issue', 'tidak', 'lpd...",rill no trust issue tidak lpdp tidak php admin,real no trust issue no lpdp no php admin,Positif,Negatif,Negatif
145869,2.027640e+18,Sat Feb 28 23:51:10 +0000 2026,0,@senggolbacoxxx @ikhsanirfansyah @LPDP_RI LPDP...,2.027890e+18,NaN,senggolbacoxxx,in,NaN,1,...,NaN,ri lpdp itu tujuannya untuk mencetak lulusan s...,ri lpdp itu tuju untuk cetak lulus yg kualitas...,"['ri', 'lpdp', 'itu', 'tuju', 'untuk', 'cetak'...","['ri', 'lpdp', 'itu', 'tuju', 'untuk', 'cetak'...",ri lpdp itu tuju untuk cetak lulus yang kualit...,RI LPDP is aimed at producing quality graduate...,Negatif,Negatif,Netral

Voting-label

In [ ]:
voting_cols = ['label_textblob', 'label_vader', 'label_senti_afinn']

In [ ]:
LPDP_clean['label_voting'] = LPDP_clean[voting_cols].mode(axis=1)[0]

In [ ]:
LPDP_clean

,conversation_id_str,created_at,favorite_count,full_text,id_str,image_url,in_reply_to_screen_name,lang,location,quote_count,...,filtered,cleaned,tweet_tokens,normalisasi,normalisasi_text,english_translation,label_textblob,label_vader,label_senti_afinn,label_voting
0,1.340000e+18,Fri Jan 01 01:33:05 +0000 2021,1,Lowongan Kerja BUMN LPDP Kemenkeu Terbaru Dese...,1.340000e+18,NaN,NaN,in,NaN,0,...,lowongan kerja bumn lpdp kemenkeu terbaru dese...,lowong kerja bumn lpdp kemenkeu baru desember,"['lowong', 'kerja', 'bumn', 'lpdp', 'kemenkeu'...","['lowong', 'kerja', 'bumn', 'lpdp', 'kemenkeu'...",lowong kerja bumn lpdp kemenkeu baru desember,New BUMN LPDP Kemenkeu job vacancies December,Positif,Netral,Netral,Netral
1,1.340000e+18,Fri Jan 01 03:01:50 +0000 2021,8,@jawafess 2020 ku wes cukup absurd tulong. 202...,1.340000e+18,NaN,jawafess,in,NaN,0,...,ku wes cukup absurd tulong ku pengen luwih ter...,ku wes cukup absurd tulong ku ken luwih tata m...,"['ku', 'wes', 'cukup', 'absurd', 'tulong', 'ku...","['ku', 'wes', 'cukup', 'absurd', 'tulong', 'ku...",ku wes cukup absurd tulong ku ken luwih tata m...,"I'm quite absurd, I can help you to win the so...",Positif,Positif,Positif,Positif
2,1.190000e+18,Fri Jan 01 03:16:45 +0000 2021,0,@indo35meme Lpdp apa ya? ï¸,1.340000e+18,NaN,indo35meme,in,NaN,0,...,lpdp apa ya,lpdp apa,"['lpdp', 'apa']","['lpdp', 'apa']",lpdp apa,what lpdp,Netral,Netral,Netral,Netral
3,1.340000e+18,Fri Jan 01 03:52:46 +0000 2021,1,Lowongan Rekrutmen LPDP Kemenkeu....Info lengk...,1.340000e+18,https://pbs.twimg.com/media/EqnhoYgVEAM5E5i.jpg,NaN,in,NaN,0,...,lowongan rekrutmen lpdp kemenkeu info lengkap,lowong rekrutmen lpdp kemenkeu info lengkap,"['lowong', 'rekrutmen', 'lpdp', 'kemenkeu', 'i...","['lowong', 'rekrutmen', 'lpdp', 'kemenkeu', 'i...",lowong rekrutmen lpdp kemenkeu info lengkap,vacancies for lpdp recruitment for the Ministr...,Positif,Netral,Netral,Netral
4,1.340000e+18,Fri Jan 01 06:33:18 +0000 2021,0,@RamaWijanarko Hai LPDPrens terima kasih atas ...,1.340000e+18,NaN,NaN,in,NaN,0,...,hai lpdprens terima kasih atas sharingnya ya s...,hai lpdprens terima kasih atas sharingnya moga...,"['hai', 'lpdprens', 'terima', 'kasih', 'atas',...","['hai', 'lpdprens', 'terima', 'kasih', 'atas',...",hai lpdprens terima kasih atas sharingnya moga...,"hi lpdprens, thank you for sharing, hopefully ...",Positif,Positif,Positif,Positif
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145865,2.027890e+18,Sat Feb 28 23:38:09 +0000 2026,0,Lpdp harvard law alumni cuman buat jd tour gui...,2.027890e+18,NaN,NaN,in,NaN,0,...,lpdp harvard law alumni cuman buat jd tour gui...,lpdp harvard law alumni cuman jd tour guide ba...,"['lpdp', 'harvard', 'law', 'alumni', 'cuman', ...","['lpdp', 'harvard', 'law', 'alumni', 'hanya', ...",lpdp harvard law alumni hanya jd tour guide ba...,lpdp harvard law alumni only act as tour guide...,Positif,Positif,Positif,Positif
145866,2.027680e+18,Sat Feb 28 23:42:18 +0000 2026,0,@bagus_muljadi Argumen bagus menggeser diskusi...,2.027890e+18,NaN,bagus_muljadi,in,NaN,0,...,muljadi argumen bagus menggeser diskusi dari m...,muljadi argumen bagus geser diskusi moral teri...,"['muljadi', 'argumen', 'bagus', 'geser', 'disk...","['muljadi', 'argumen', 'bagus', 'geser', 'disk...",muljadi argumen bagus geser diskusi moral teri...,muljadi good argument slide moral discussion a...,Positif,Positif,Positif,Positif
145867,2.027680e+18,Sat Feb 28 23:44:18 +0000 2026,0,@bagus_muljadi 4. kolaborasi LPDP Kemendikbud ...,2.027890e+18,NaN,bagus_muljadi,in,NaN,0,...,muljadi kolaborasi lpdp kemendikbud untuk pipe...,muljadi kolaborasi lpdp kemendikbud untuk pipe...,"['muljadi', 'kolaborasi', 'lpdp', 'kemendikbud...","['muljadi', 'kolaborasi', 'lpdp', 'kemendikbud...",muljadi kolaborasi lpdp kemendikbud untuk pipe...,muljadi collaboration of the Ministry of Educa...,Netral,Positif,Positif,Positif
145868,2.027010e+18,Sat Feb 28 23:45:59 +0000 2026,0,@ejaeyun Rill no trust issue ga lpdp ga php Mi...,2.027890e+18,https://pbs.twimg.com/tweet_video_thumb/HCSF_z...,ejaeyun,en,NaN,0,...,rill no trust issue ga lpdp ga php min,rill no trust issue ga lpdp ga php min,"['rill', 'no', 'trust', 'issue', 'ga', 'lpdp',...","['rill', 'no', 'trust', 'issue', 'tidak', 'lpd...",rill no trust issue tidak lpdp tidak php admin,real no trust issue no lpdp no php admin,Positif,Negatif,Negatif,Negatif
145869,2.027640e+18,Sat Feb 28 23:51:10 +0000 2026,0,@senggolbacoxxx @ikhsanirfansyah @LPDP_RI LPDP...,2.027890e+18,NaN,senggolbacoxxx,in,NaN,1,...,ri lpdp itu tujuannya untuk mencetak lulusan s...,ri lpdp itu tuju untuk cetak lulus yg kualitas...,"['ri', 'lpdp', 'itu', 'tuju', 'untuk', 'cetak'...","['ri', 'lpdp', 'itu', 'tuju', 'untuk', 'cetak'...",ri lpdp itu tuju untuk cetak lulus yang kualit...,RI LPDP is aimed at producing quality graduate...,Negatif,Negatif,Netral,Negatif

In [ ]:
path='/content/drive/MyDrive/Int Conference/Data Label/'

In [ ]:
LPDP_clean.to_csv(f'{path}LPDP_cleaned_label.csv', index=False)